### ISSUE TITLE
FEATURE REQEST: ReadOut Dallas sensors

### ISSUE THREAD

**Issue by alexpthe1** [tp1de/ioBroker.ems-esp#1]
It would be nice if the connected dallas sensors would be reported to iobroker

**Comment by tp1de** [comment]
I am preparing an update with dallas sensors read.
Since I have done other major coding changes it will take some days until I will release the new version.

**Comment by tp1de** [comment]
@alexpthe1 
The new version 0.9.8 is supporting dallas sensors. Please test if it's working.

**Comment by alexpthe1** [comment]
first of all, thank you for  your great work and fast response!
Unfortunately it is not working. 
The IDs are Reported but the value not (stays NULL)

https://paste.pics/3329d5a0b02b8d965661279edcd3b15f
https://paste.pics/ebacf7540dd52ae18c92c72b378ed7fa

**Comment by tp1de** [comment]
What is returned by  http://ems-esp/api/dallassensor/ ?

**Comment by tp1de** [comment]
That is my data:
{
  "sensor1": {
    "id": "28-FF04-CFC4-1604",
    "temp": 25.6
  },
  "sensor2": {
    "id": "28-FF3B-04C5-1604",
    "temp": 25.4
  }

**Comment by alexpthe1** [comment]
// 20211124230239
// http://ems-esp/api/dallassensor/

{
  "28-C808-07D6-013C": 43,
  "28-4012-07D6-013C": 83.5
}

**Comment by tp1de** [comment]
That's the reason for the null values. Which ems-esp-version are you using?

**Comment by alexpthe1** [comment]
EMS-ESP Version
v3.2.1

with a Device (Platform / SDK)
ESP32 / v3.3.5-1-g85c43024c

**Comment by tp1de** [comment]
@proddy seems to have changed the api format for dallassensors. Actual dev version is v3.3.0b10  that's what I use.
I will try to adjust the ioBroker adapter to accept the "old" format as well.

**Comment by tp1de** [comment]
I just uploaded an updated version. Please check if it is working now?

**Comment by alexpthe1** [comment]
yep! thank you, again great work and even greater support

**Comment by tp1de** [comment]
I learned that it is quite a challenge to permanently adjust the adapter to all the changes done by @proddy .....

I will close this issue now.

**Comment by proddy** [comment]
That is a probably a mistake in EMS-ESP.The format should be the same. I'll look into it.
