### ISSUE TITLE
Custom Entities shown under folder "unknown" and custom entity not writeable

### ISSUE THREAD

**Issue by UlfHRO** [tp1de/ioBroker.ems-esp#102]
I added today my first custom entities and reading via ems-esp and iobroker works fine, but the folder in ioBroker is named "unknown". Is this the correct behaviour...?

A custom entity in that folder "unknown" is correctly set to be writeable in ems-esp and can also be written in ems-esp, but can not be written from ioBroker?!

B Which version of the ems-esp adapter are you using? 
4.7.0

![IMG_0357](https://github.com/user-attachments/assets/a86c1ec3-4e5d-4e7f-9b24-878ca0514883)

**Comment by tp1de** [comment]
which ems-esp firmware version are you using?

**Comment by UlfHRO** [comment]
Version 3.7.0 dev.30

------------------
Ulf Hirsekorn
------------------
________________________________
Von: Thomas ***@***.***>
Gesendet: Samstag, August 17, 2024 10:24 AM
An: tp1de/ioBroker.ems-esp ***@***.***>
Cc: UlfHRO ***@***.***>; Author ***@***.***>
Betreff: Re: [tp1de/ioBroker.ems-esp] Custom Entities shown under folder "unknown" and custom entity not writeable (Issue #102)


which ems-esp firmware version are you using?

**Comment by tp1de** [comment]
I found the mistake but I am just thinking how to correct. Up to yet custom elements where read and by device_id the right device was allocated. So custom elements for thermostat where under thermostat or heatingCircuits. Since devices where renamed the allocation was not working anymore ... so undefined.

Shall I keep this or shall custom elements be under custom?
What do you think?

**Comment by tp1de** [comment]
I think I will use custom object structure for custom elements ....

**Comment by UlfHRO** [comment]
👍

—————————
Ulf Hirsekorn
—————————
________________________________
Von: Thomas ***@***.***>
Gesendet: Samstag, August 17, 2024 10:53 AM
An: tp1de/ioBroker.ems-esp ***@***.***>
Cc: UlfHRO ***@***.***>; Author ***@***.***>
Betreff: Re: [tp1de/ioBroker.ems-esp] Custom Entities shown under folder "unknown" and custom entity not writeable (Issue #102)


I think I will use custom object structure for custom elements ....

**Comment by UlfHRO** [comment]
Does ot mean I can Not write to custom entities...? Or is it just now a bug...?
Thanks....

—————————
Ulf Hirsekorn
—————————
________________________________
Von: Thomas ***@***.***>
Gesendet: Samstag, August 17, 2024 10:49 AM
An: tp1de/ioBroker.ems-esp ***@***.***>
Cc: UlfHRO ***@***.***>; Author ***@***.***>
Betreff: Re: [tp1de/ioBroker.ems-esp] Custom Entities shown under folder "unknown" and custom entity not writeable (Issue #102)


I found the mistake but I am just thinking how to correct. Up to yet custom elements where read and by device_id the right device was allocated. So custom elements for thermostat where under thermostat or heatingCircuits. Since devices where renamed the allocation was not working anymore ... so undefined.

Shall I keep this or shall custom elements be under custom?
What do you think?

**Comment by tp1de** [comment]
> Does ot mean I can Not write to custom entities...? Or is it just now a bug...? Thanks....

another bug

**Comment by UlfHRO** [comment]
Ok... Thanks for looking into this and for your time and effort...!

—————————
Ulf Hirsekorn
—————————
________________________________
Von: Thomas ***@***.***>
Gesendet: Samstag, August 17, 2024 11:40 AM
An: tp1de/ioBroker.ems-esp ***@***.***>
Cc: UlfHRO ***@***.***>; Author ***@***.***>
Betreff: Re: [tp1de/ioBroker.ems-esp] Custom Entities shown under folder "unknown" and custom entity not writeable (Issue #102)


Does ot mean I can Not write to custom entities...? Or is it just now a bug...? Thanks....

another bug

**Comment by tp1de** [comment]
I haven't used custom elements in ioBroker for a long time anymore ... since I moved to Home Assistant.
Writing was never enabled - just reading. It should work now with version 4.7.2.

Please test and report.

**Comment by UlfHRO** [comment]
Hi Thomas,
Tested with 4.7.2. and I can confirm both is now correct:

  *   Custom entities in folder "custom"
  *   Custom entity is writable

Thanks a lot and "case closed"!
I hope you will maintain this adapter even you changed to HA!?!
Best regards,
p.s. unfortunately I have to open another ticket for DHW control commands... Sorry...

------------------
Ulf Hirsekorn
------------------
________________________________
Von: Thomas ***@***.***>
Gesendet: Samstag, August 17, 2024 12:19 PM
An: tp1de/ioBroker.ems-esp ***@***.***>
Cc: UlfHRO ***@***.***>; Author ***@***.***>
Betreff: Re: [tp1de/ioBroker.ems-esp] Custom Entities shown under folder "unknown" and custom entity not writeable (Issue #102)


I haven't used custom elements in ioBroker for a long time anymore ... since I moved to Home Assistant.
Writing was never enabled - just reading. It should work now with version 4.7.2.

Please test and report.
