### ISSUE TITLE
Thermostat DHW control commands not working correctly

### ISSUE THREAD

**Issue by UlfHRO** [tp1de/ioBroker.ems-esp#103]
**Describe the bug**  
Controlling Thermostat DHW commands is not working correctly (anymore). I am pretty sure it was working correct with earlier releases...
For example:
- ems: dhw charge
- ems: dhw circulation pump mode
- ems: dhw disinfecting
- ems: dhw mode
If variable is writen in ioBroker the value change correctly to the new value, but after a few seconds it goes back to the old value and then after many seconds back to the correct new value.
This behavior I see only with thermostat dhw1. All other commands work as expected without this strange toggle behaviour...

** Releated to gateway(s) and/or adapter configuration

B Which version of the ems-esp adapter are you using? 

4.7.2

C is this bug related to the ems-esp or km200 gateway? (which gateway hardware are you using?)
D please descripe software versions of the ems-esp firmware and/or km200 gateway 

3.7.0-dev.30

E please post screenshot(s) of the adapter config

**Expected behavior**  

**Additional context**

**Comment by tp1de** [comment]
Polling and writing are not synchronized. How fast is your polling cycle?

I understand that writing works .... or?

**Comment by UlfHRO** [comment]
Yes, finally writing works, but value toggles twice...
Polling 15 sec...

—————————
Ulf Hirsekorn
—————————
________________________________
Von: Thomas ***@***.***>
Gesendet: Samstag, August 17, 2024 5:06 PM
An: tp1de/ioBroker.ems-esp ***@***.***>
Cc: UlfHRO ***@***.***>; Author ***@***.***>
Betreff: Re: [tp1de/ioBroker.ems-esp] Thermostat DHW control commands not working correctly (Issue #103)


Polling and writing are not synchronized. How fast is your polling cycle?

I understand that writing works .... or?

**Comment by tp1de** [comment]
I tested myself. I do have this effect seldom. 
It takes a bit time when writing values to the gateway. 
It could happen that in the meantime the old values are still processed by parallel read.
Read is per device and then all values of the device are written sequentially.
I can not change this logic.

**Comment by UlfHRO** [comment]
Hi Thomas, I hear what you are saying, but the behaviour is only for commands in thermostat/dhw and happens always (not sometimes). For all other commands I never saw that toggle at all... It looks that "something" is different with dhw commands and I am pretty confident this was not the case a few weeks ago...

What is your recommended minimum polling time...?

Thanks and have a good evening...

**Comment by tp1de** [comment]
I use 15 seconds as well, and I can't confirm any of your problems. 
Dhw entities are the same as others. But normally, you would not change often. 
Please test with 60 seconds if there is the same behavior

**Comment by UlfHRO** [comment]
Hi Thomas,
Same with 60 seconds, but less often...
🤔

**Comment by tp1de** [comment]
Which model of ems-esp gateway are you using?

**Comment by UlfHRO** [comment]
S32

------------------
Ulf Hirsekorn
------------------
________________________________
Von: Thomas ***@***.***>
Gesendet: Saturday, August 17, 2024 8:58:29 PM
An: tp1de/ioBroker.ems-esp ***@***.***>
Cc: UlfHRO ***@***.***>; Author ***@***.***>
Betreff: Re: [tp1de/ioBroker.ems-esp] Thermostat DHW control commands not working correctly (Issue #103)


Which model of ems-esp gateway are you using?

**Comment by tp1de** [comment]
Ulf I do not know why you are facing this behavior.

I have done more than 30 changes.
No problems. Using iobroker object browser 1st update is red and after next poll the state is confirmed and turns white.

**Comment by tp1de** [comment]
New day with new insights:

I have done some more tests. 
I recognized that while sending an http post/put with changes to the gateway the read with http get is not changed immediately - just when the next telegram with actual data is read.

For the thermostat dhw entities this takes longer than for other entities.
This is not and ioBroker adapter issue. I will open an issue on ems-esp.

**Comment by UlfHRO** [comment]
Thanks Thomas, appreciated...!
Lets wait for the ems-esp-team...

—————————
Ulf Hirsekorn
—————————
________________________________
Von: Thomas ***@***.***>
Gesendet: Sonntag, August 18, 2024 10:22 AM
An: tp1de/ioBroker.ems-esp ***@***.***>
Cc: UlfHRO ***@***.***>; Author ***@***.***>
Betreff: Re: [tp1de/ioBroker.ems-esp] Thermostat DHW control commands not working correctly (Issue #103)


New day with new insights:

I have done some more tests.
I recognized that while sending an http post/put with changes to the gateway the read with http get is not changed immediately - just when the next telegram with actual data is read.

For the thermostat dhw entities this takes longer than for other entities.
This is not and ioBroker adapter issue. I will open an issue on ems-esp.

**Comment by tp1de** [comment]
Ulf, the latest dev.32 version of ems-esp firmware should work.
Can you confirm please.

**Comment by UlfHRO** [comment]
Hi Thomas, Will do tomorrow when back home... Will let you know asap...
Thanks...

—————————
Ulf Hirsekorn
—————————
________________________________
Von: Thomas ***@***.***>
Gesendet: Tuesday, August 20, 2024 1:01:29 PM
An: tp1de/ioBroker.ems-esp ***@***.***>
Cc: UlfHRO ***@***.***>; Author ***@***.***>
Betreff: Re: [tp1de/ioBroker.ems-esp] Thermostat DHW control commands not working correctly (Issue #103)


Ulf, the latest dev.32 version of ems-esp firmware should work.
Can you confirm please.

**Comment by UlfHRO** [comment]
Hi Thomas,
Yes, confirmed, it works as expected with 3.7.0-dev.32...!
Thanks a lot!
Regards,
Ulf
