### ISSUE TITLE
Confusing config. description in readme.md

### ISSUE THREAD

**Issue by Hans-JR** [tp1de/ioBroker.ems-esp#11]
**Describe the bug**  
The chapter "important settings in EMS-ESP:" 
instructs to "The Enable API write commands settings within ems-esp has to be enabled"

Unfortunately I cannot find this in the latest stable version of the EMS-ESP setting (Ver. 3.4.4)
The only setting I can see is the checkbox "Enable Read only mode (blocks all outgoing EMS Tx write commands)"
Is this the right one? If yes, please correct this in the *.md file.

**Comment by tp1de** [comment]
Yes there are permanent changes within ems-esp settings and functionality. I can not provide updates every time in respect for this adapter. When version 3.5 is released I will update the readme accordingly.

> The only setting I can see is the checkbox "Enable Read only mode (blocks all outgoing EMS Tx write commands)"
> Is this the right one? If yes, please correct this in the *.md file.
No Read Only will not work for updates.
Formatting is important
![image](https://user-images.githubusercontent.com/36480251/206851972-9f4b47e7-2a5b-4965-ab35-18d707764162.png)

And for writing either enabling
![image](https://user-images.githubusercontent.com/36480251/206852007-7b0b855a-939d-4016-baa1-2029ecf868bc.png)
or setting access token 
![image](https://user-images.githubusercontent.com/36480251/206852058-9f3b3871-7d7f-4042-83b1-92417655ae8c.png)
