### ISSUE TITLE
Junkers HT3 WW-Speichertemperatur oben wird nicht mehr aktualisiert. 

### ISSUE THREAD

**Issue by Matzebhv** [tp1de/ioBroker.ems-esp#14]
Anscheinend funktioniert seit dem 17.02 die Aktualisierung der entsprechenden DP nicht mehr. Mir ist das jetzt erst aufgefallen da die Sonnentage wieder zunehmen.

Kann das mit einem Adapterupdate zu tun haben? EMS-Version ist die 3.5.0
![ems1](https://user-images.githubusercontent.com/20025244/221406719-77481ba9-ee91-47ea-b159-078f9d061a97.png)
![ems2](https://user-images.githubusercontent.com/20025244/221406724-a1feb3d6-8316-4d27-bd87-8c6440ee3e28.png)
![ems3](https://user-images.githubusercontent.com/20025244/221406772-0b2ece48-928c-48d5-a000-741dc3e16dfb.png)

Gruß
Matze

**Comment by Matzebhv** [comment]
Habe grade geprüft, am 17. habe ich das Update auf die 1.22 eingespielt. Nach einem downgrade auf die 1.21 werden die Werte wieder geliefert.
Es handelt sich hier also um einen Bug in der 1.22

**Comment by tp1de** [comment]
> Habe grade geprüft, am 17. habe ich das Update auf die 1.22 eingespielt. Nach einem downgrade auf die 1.21 werden die Werte wieder geliefert.
> Es handelt sich hier also um einen Bug in der 1.22

Danke für den Hinweis @Matzebhv. Hatte ich noch gar nicht bemerkt, da im fast nur noch Homeassistant benutze.
Ist im Github korrigiert. Leider funktioniert aktuell das Release Script nicht (Fehlermeldungen), so dass ich 1.23 scheinbar nicht freigeben kann. Ich versuche es heute Abend nochmal. Die Version 1.22 ist eh nur interessant, wenn mehr als 1 Mischer vorhanden ist.

**Comment by Matzebhv** [comment]
Habe mir das mal von git gezogen, funktioniert!
Danke für den schnellen Fix und dir noch einen schönen Sonntag.
Gruß
Matze
