### ISSUE TITLE
switchPrograms and holidayModes

### ISSUE THREAD

**Issue by Tim19791** [tp1de/ioBroker.ems-esp#148]
Hello, can you please integrate the function "search for switchPrograms and holidayModes" into the current versions with a warning message? For me it works with v4.7.2 without any problems.
Thanks for the great work.

**Comment by tp1de** [comment]
I do not want to reactivate this function. The switchPrograms and holidayModes should be integrated into the ems-esp firmware.
I am testing since a while with @MichaelDvP .

Please download and install the latest testversion from https://github.com/MichaelDvP/EMS-ESP32/releases 
and report here if it works: https://github.com/emsesp/EMS-ESP32/issues/1594#issuecomment-2495453376

**Comment by tp1de** [comment]
I got no reaction from you.

**Comment by Tim19791** [comment]
Wie schon gesagt ich hatte auch mit v4.7.2 keine Probleme. und auch mit der 5.0.6 geht es. Aber du kannst ja eine Schalter hinzufügen zum Aktivieren oder Deaktivieren. Es gibt bestimmt auch User die das nicht benötigen.

**Comment by tp1de** [comment]
In den neuen Versionen ist das wieder rausgenommen. Dann bleibe bei der 5.06 aus dem GH bis die Funktionen sauber in EMS-ESP implementiert sind.

**Comment by Tim19791** [comment]
Perfekt wäre wenn man sich die Datenpunkte einzeln auswählen kann, ich Persönlich brauche Warmwasser nicht dafür hätte ich lieber hc1 A und B . Vielleicht lässt sich dadurch  Lese- und Schreibvorgänge einsparen, wenn man nur das Aktiviert was man auch benötigt.

**Comment by Tim19791** [comment]
in der EMS gefällt es mir nicht so da es immer mit umschaltet. Fest Programme A/B sind besser

**Comment by tp1de** [comment]
> in der EMS gefällt es mir nicht so da es immer mit umschaltet. Fest Programme A/B sind besser

Das scheitert aktuell am Speicher des esp32.

**Comment by tp1de** [comment]
Das Lesen der Switchprogramme und Holidaymodes über Raw Telegramme ist fehlerbehaftet. Ich muss bis zu 12 Mal versuchen,  bis ich Ergebnisse habe. 
Ebenso heim Schreiben. Es werden jede Menge Fehler im Log angezeigt. 
Es funktioniert so gerade eben bei mir.

Auf eigene Gefahr und ohne Support kannst du die Funktion aktivieren, wenn du "***" der ems-esp Adresse voranstellst und den Expertenmodus auswählst.
Dort kannst du die Telegramme auswählen.

**Comment by Tim19791** [comment]
ok, habe ich mir angesehen aber noch mit v5.0.6 Würde gern mal probieren was passiert wenn ich progA mit auslese,  aber wie bekomme ich hc1.switchPrograms.A dazu? Automatisch hat er es nicht erkannt. 
![Screenshot 2024-12-26 204048](https://github.com/user-attachments/assets/572bb388-0012-4b7d-9689-33b6c6703920)

Habe eben nochmal 3 mal das Programm geändert hat er alles übernommen und keine Fehler im log, und auch beim Datenverkehr keine Fehler:

![Screenshot 2024-12-26 204758](https://github.com/user-attachments/assets/71f78753-ca33-440a-b6cd-da06e1a863ad)

**Comment by Tim19791** [comment]
Ich habe mal testweise ein Textsystem aufgesetzt, jetzt mit v5.1.1.
Sobald ich den Haken setze bei: "Aktivieren der Suche nach zusätzlichen EMS+-Entitäten (switchTimes & HolidayModes) – Schreibzugriff erforderlich" bekomme ich Fehlermeldung:  

2024-12-26 22:02:09.656 | info | EMS+ entity new search initialized - this might take several minutes
2024-12-26 22:03:27.810 | error | post: http://192.168.0.9/api/system/send AxiosError: Request failed with status code 401

**Comment by tp1de** [comment]
Access Token eingegeben?

**Comment by Tim19791** [comment]
ja, hatte ich vergessen.
So stand jetzt: v5.1.1.  musste leider alle Entitäten manuell eingeben da die Auto suche nur bis v4.7.2 geht.
habe mal alles eingetragen:
 
![Screenshot 2024-12-26 233825](https://github.com/user-attachments/assets/61c128a9-dffa-41c6-acf8-59fca1d43ed0)

habe 2 mal erfolgreich geschrieben ohne Fehler!   werde jetzt beobachten.


info: ich hatte auch Probleme als ich beide Module angeschlossen hatte  (ems+original)

**Comment by tp1de** [comment]
Autosuche geht nur wenn alle Daten gelöscht werden (leer sind)

**Comment by Tim19791** [comment]
war alle leer hatte neues System zum testen aufgesetzt. erst als ich auf v4.7.2 zurückgegangen bin hat er sie wieder gefunden.

Ich habe mir mal zu Testen  ein Skript gemach das jede Minute ein neues progA geschrieben hat, das habe ich jetzt 90 min laufen lassen.
hat alles funktioniert keine fehler:
![Screenshot 2024-12-27 094106](https://github.com/user-attachments/assets/fe1b7b29-f728-4d12-9194-08d0a7e818e2)
