### ISSUE TITLE
KM200 Kesselstarts (1h, 24h) werden nicht mehr angezeigt (0)

### ISSUE THREAD

**Issue by Track4123** [tp1de/ioBroker.ems-esp#160]
Hi. Musste mein System neu Aufsetzten und seitdem werden die Kesselstart (letzte Stunde / letzte 24 Stunden) nicht mehr angezeigt.
Habe alles aktiviert wie es sein sollte. HistoryDatenbank ist auch aktiv.
Hast du eine Idee warum die nicht mehr kalkuliert werden?
Viele Grüße!

**Comment by tp1de** [comment]
Also km200 mit History Adapter?
Wie hast Du denn neu aufgesetzt? Mit Backup / Restore?

**Comment by tp1de** [comment]
Ich habe den Fehler korrigiert und eine neue Version hochgeladen (5.1.0)

**Comment by Track4123** [comment]
Hi. Erstmal frohe Weihnachten. Ich teste mal die neue Version.. Ne, hatte kein Backup zurück spielen können, hatte es zerschossen🥳 Ich gebe Feedback.

**Comment by Track4123** [comment]
Hi, habe das Update installiert. Für Starts pro 1h und On per Hour sieht es gut aus.
Für die Starts in 24h, müssen erst 24h Stunden aufgezeichnet sein oder sollte gleich die letzten Starts mit einbezogen werden?
![image](https://github.com/user-attachments/assets/47cfa713-45df-4d07-bb1d-79dac84e67e2)
Beispiel hier wäre 8 Starts gewesen
![image](https://github.com/user-attachments/assets/6c41620c-901c-4c9d-b0d4-4db12303c8c4)
Grüße!

**Comment by tp1de** [comment]
Habe ich hoffentlich mit 5.1.1 korrigiert

**Comment by Track4123** [comment]
Leider nicht ganz, in der Stunde passt, aber in 24 Stunden zeigt er 9118 an was ja hoffentlich nicht wahr ist😀 
![image](https://github.com/user-attachments/assets/c310eb7a-0896-49bf-b30f-cf7dd3db1f4d)
hast du eine Idee?

**Comment by Track4123** [comment]
Mm2, jetzt ist es Ok!? Braucht er ne Weile um die Daten zu lesen?

![image](https://github.com/user-attachments/assets/5762f913-9105-4ee6-aad4-0154a0302783)

**Comment by tp1de** [comment]
> Mmh , jetzt ist es Ok!? Braucht er ne Weile um die Daten zu lesen?

Das lesen der Historie mit dem History Adapter scheint nicht richtig zu funktionieren, wenn weniger als 24 Stunden Daten vorhanden sind. Ich verwende ioBroker Standard-Funktionen die für alle Datenbanken gelten.
Jetzt sind bei Dir 24 Stunden vorhanden, deshalb stimmt der Wert.

Ich wundere mich nur über 31 Starts in 24 Stunden bei den aktuellen Aussentemperaturen.
Ich habe 3 und alle 3 sind bedingt durch Warmwasserbereitung. 
Du solltest mal schauen, ob die Heizkurve verändert werden kann.

**Comment by Track4123** [comment]
Hi, ist jetzt gut. Wie gesehen hat es eine Weile gedauert. Wg. den 31, ich weiß, genau mein Probelm, das Teil ist viel zu groß! Wurden falsch beraten . Hydraulik ist auch nicht gut. Naja, beim nächsten mal wissen wir es besser. Heizkurve ist auf 44 bei 0 Grad mit Heizkörpern, ich würde noch weiter runter können, aber dann tacktet das Ding noch mehr 🙃 Geht jetzt alles! Guten Rutsch!
