### ISSUE TITLE
Wirkungsgradberechnung 

### ISSUE THREAD

**Issue by joschi71r** [tp1de/ioBroker.ems-esp#17]
Hallo,
ich möchte gerne die Wirkungsgradberechnung im EMS-ESP Adapter aktivieren, habe aber keinen KM200.
Habe mir den Quellcode auf Github angesehen. Wenn ich es richtig verstehe müsste die Berechnung auch ohne KM200 funktionieren.
Mein Problem ist die Rücklauftemperatur. Bei meiner Anlage gib es diesen Wert nicht (ZSB 24-5). Daher habe ich einen Dallassensor als Rücklauffühler.
Frage: währe es möglich in der Adapterkonfiguration die Rücklauftemperatur auf einen anderen Datenpunkt umzulenken?
Ich weiß, dass das einer Anpassung im Adapter bedarf. Aber vielleich würden sich andere Benutzer auch darüber freuen.
Viele Grüße und vielen Dank für die tolle Arbeit
joschi71r

**Comment by tp1de** [comment]
Im Moment möchte ich erst einmal keine Änderungen mehr einpflegen. Ich überlege mal, wann ich das ggfs. realisiere.
Die letzten Änderungen haben immer mal wieder bei einzelnen Anwendern nicht funktioniert und es war dann viel Aufwand das zu korrigieren.

**Comment by tp1de** [comment]
... und wenn keine Rücklauftemperatur vorhanden ist, dann wird diese mit Vorlauf - 10°C angenommen. So falsch ist das bestimmt nicht.

**Comment by tp1de** [comment]
Ich habe jetzt doch mal die Logik komplett umgeschrieben, so dass für die Modulation, Vorlauf und Rücklauf-Temperatur jeweils beliebige states (auch außerhalb des Adapters) eingegeben werden können. Fehler werden jetzt nicht mehr angezeigt.

Lade mal vom GH und teste  ....

**Comment by joschi71r** [comment]
Konnte erst jetzt testen.
Es sieht aus, als ob alles funktioniert.
Tolle Arbeit.
Vielen Dank
