### ISSUE TITLE
error ems read status

### ISSUE THREAD

**Issue by cyberoner1** [tp1de/ioBroker.ems-esp#18]
Hallo,
Habe eine Bosch 7001 Wärmepumpe. Die Haken sind alle auf Grün, aber es werden keine Daten gelesen. Im Protokol steht nur 
error ems read status
Eine Idee dazu?

**Comment by tp1de** [comment]
???? Was genau hast Du denn? EMS-ESP Gateway???
Wenn ja, dann poste bitte die Adapter Config.

**Comment by cyberoner1** [comment]
So ganz werde ich aus dem Thema Bosch Wärmepumpe niucht schlau.
Ich habe das Lan Modul der Wärmepumpe mit meiner FritzBox Verbunden. Die EasyRemote App von Bosch auf meinem Mobile installiert, das PW gesetzt und kann die Daten in der App sehen.
Die 2 PAsswörter in der App eingetragen und wie auf dem Bild konfiguriert
![image](https://user-images.githubusercontent.com/24601600/230376687-f7091515-d114-48c5-b0d9-5396d7c0779d.png)

In Objekte alles mit InfluxDB gekoppelt, aber schreibt keine Werte. Bei meinen Objekten steht z.B. bei actualtemp eine -99

Ich muss dazu sagen, dass ich erst grade mit IOBroker angefangen habe, daher bitte nachsicht :)

**Comment by tp1de** [comment]
2 Fragen:

1. Hast Du eine EMS-ESP Gateway von BBQKees? - Nur dann funktioniert ems-esp
2. Hast Das private Passwort wie im Readme erklärt mit der MyDevice App gesetzt? Nur damit funktioniert das km200 Gateway
