### ISSUE TITLE
Integrierung - Buderus KM200 HRV für Lüftungsanlagen

### ISSUE THREAD

**Issue by mbhomie007** [tp1de/ioBroker.ems-esp#2]
Hallo, 
Ich habe folgenden Wunsch:
Vielleicht könnte dies integriert werden.

Leider ist in dem Adapter das Buderus KM200 HRV Gateway für Logavent Lüftungsanlagen nicht integriert.

Die Daten lassen sich nicht richtig auslesen, einige Daten werden aber abgegriffen.
Die Verbindung wurde erfolgreich über den Adapter hergestellt.
Nur kann man mit den Daten nichts anfangen...

![Screenshot 2022-01-31 162736](https://user-images.githubusercontent.com/64688879/151821796-b7d503d6-6409-4efd-80d0-7102b1c792c6.jpg)

Habe eine Buderus HRV2 Lüftungsanlage in Verbindung mit dem KM200 HRV und der Buderus App "My Vent".

Ich bin gerne bereit bei der Integrierung zu unterstützen und zu testen.

**Comment by tp1de** [comment]
Ich bin mir nicht sicher, ob Du überhaupt einen km200 / IP-Inside installierst hast, oder nur den mx300.
Den kenne ich nicht. Das Gateway wird erkannt mit RS485 serieller Modbus Anbindung. 
Ist also erst einmal nicht an den EMS-Bus angebunden sondern per Modbus.

Das km200 API-Polling braucht definierte Einstiegspunkte. Aktuell sind das:
"heatSources", "dhwCircuits", "heatingCircuits", "system", "notifications", "gateway", "solarCircuits"

Ich habe einen neuen Einstiegspunkt im Adapter eingebbar gemacht. Kannst ja mal mit "ventilationCircuits" oder ähnlichem versuchen, ob Du Erfolg hast.  Und lass den Adapter im Debug-Mode laufen und poste mal das Log.

**Comment by mbhomie007** [comment]
> Ich bin mir nicht sicher, ob Du überhaupt einen km200 / IP-Inside installierst hast, oder nur den mx300.

Das KM 200 HRV habe ich installiert. 

https://www.buderus.de/de/produkte/catalogue/alle-produkte/103131_gateway-logamatic-web-km100- 

![Screenshot_20220131-191933_Chrome.jpg](https://user-images.githubusercontent.com/64688879/151850715-916852c2-01f6-4c43-8441-3407491e1713.jpg)

> Ich habe einen neuen Einstiegspunkt im Adapter eingebbar gemacht. 
> Den kannst Du vom Github installieren - habe die Versionsnummer nicht geändert.

Das heißt dann einfach nochmal drüber installieren? 


Vielen Dank für die schnelle Antwort.

**Comment by tp1de** [comment]
Ja einfach nochmal aus Github installieren. Nicht aus dem. ioBroker repository.

Das km200 HRV ist eine angepasste Variante mit eigener Firmware und Modbusanbindung.

Jetzt gilt es den Einstiegspunkt herauszufinden ...
Viele Grüße Thomas Petrick

**Comment by mbhomie007** [comment]
Habe nun die Version direkt von GitHub installiert:

![image](https://user-images.githubusercontent.com/64688879/151920300-d6fd133d-260b-444d-bcc3-ec40885b1bd8.png)

![image](https://user-images.githubusercontent.com/64688879/151920428-00d24334-5b4a-46d8-b637-1050e5bdfba2.png)

An den Datenpunkten hat sich nichts geändert...

>Kannst ja mal mit "ventilationCircuits" oder ähnlichem versuchen, ob Du  Erfolg hast.
Wie kann ich danach suchen? Habe keine neuen Datenpunkte gefunden.

**Comment by mbhomie007** [comment]
Habe nun die Version direkt von GitHub installiert.

![image](https://user-images.githubusercontent.com/64688879/151920894-62335f32-2304-4952-9359-e1bfa2c69937.png)

"ventilationCircuits" wird nicht gefunden.

**Comment by mbhomie007** [comment]
Sorry, bin auf den falschen Button gekommen...
Kannst du das Ticket bitte nochmal öffnen?

**Comment by mbhomie007** [comment]
Sooo habe nun nur "ventilation" als neuer Einstiegspunkt eingeben.

![image](https://user-images.githubusercontent.com/64688879/151921756-3b38bf2e-e8c8-4b3d-9751-9c1a82e70d68.png)

Nur Recordings bleibt auf null

![image](https://user-images.githubusercontent.com/64688879/151921843-deba7c0a-39f5-4a6f-8806-d06cf28ddb78.png)

Ansonsten vielen Dank für deinen tollen Support, alle Datenpunkte werden nun ausgelesen. 💯 

![image](https://user-images.githubusercontent.com/64688879/151921924-0e49a429-837d-42a9-969e-b0359e98cd28.png)

![image](https://user-images.githubusercontent.com/64688879/151921953-1cc054c4-f234-4340-b8bb-6e160e12d8ee.png)

Wirst du dann eine neue Version veröffentlichen?

**Comment by tp1de** [comment]
Gut zu hören, dass der Einstiegspunkt "ventilation" funktioniert.

Das recordings keine Daten liefert ist eigentlich klar, da ich bei einer Lüftungsanlage dies auch nicht erwarten würde.
Es sei denn, Du siehst Energieverbräuche in der myVent App oder im Buderus Portal ....

Ich mach heute im Laufe des Tages eine neue Beta-Version wo ich "ventilation" mit aufnehme und die Eingabe wieder entferne.
Sollte also Morgen im Repository sein.

**Comment by mbhomie007** [comment]
Vielen Dank für deine Zeit & Arbeit!! 👌
1A! 💯
