### ISSUE TITLE
Dallas-Sensoren werden nicht in den iobroker übernommen.

### ISSUE THREAD

**Issue by MatzeFro** [tp1de/ioBroker.ems-esp#22]
Hallo Thomas,
ich habe ein neues Problem festgestellt .
ich habe den Haken bei "Dallas" gesetzt aber die Thermometer werden nirgends angezeigt (über MQTT aber schon).
http://ems-esp/api/dallassensor/ ergibt:
{
  "message": "unknown device"
}

http://ems-esp/api/temperaturesensor/
{
  "28-38A6-5704-183C": 45.1,
  "28-6694-5704-653C": 38.4,
  "28-B9F1-5704-823C": 38.1,
  "WW Vorlauf": 46.3,
  "Raumtemperatur": 33.6
}

ich Nutze v3.6.0-dev.12

Gruß und Dank
Matthias

**Comment by tp1de** [comment]
Ja wie sagen die beiden Entwickler zu dieser Art von eigentlichen Änderungen: Ist halt eine dev Version und da gibt es solche grundsätzliche Änderungen. Ich habe langsam keine Lust mehr, immer nachzubessern und überlege nur noch produktiv Versionen zu unterstützen. Das betrifft auch den ioBroker JS-Controller.

**Comment by MatzeFro** [comment]
OK - bin dann erst mal wieder auf 3.5.1 - aber die Änderung wird ja mit 3.6 kommen :)

**Comment by tp1de** [comment]
Lass den Issue ruhig offen .... irgendwann muss ich den Adapter ja anpassen. Aktuell komme ich nur nicht dazu ...

**Comment by MatzeFro** [comment]
Hallo Thomas,
habe soeben mal die Version v1.33.0 getestet und die EMS-ESP mit v3.6.0-dev.12 :
erster Test war auch Erfolgreich.
Die Dallas Sensoren werden nun (leider) als ems-esp.0.temperaturesensor eingelesen.
Da ich ja erst anfange nicht schlimm. Aber es wäre sicher auch charmant gewesen die dann weiter unter ems-esp.0.dallas zu speichern. 
Falls man die schon länger nutzt und diese langfristig in der Datenbank für z.Bsp. Grafana gespeichert hatte.

 Gruß

**Comment by tp1de** [comment]
Gut, dass es funktioniert. Ich kann zur Zeit nicht selber testen. Die EMS-ESP Entwickler ändern ja regelmäßig die Namen. Auch für Homeassistant gibt es Beschwerden. Beim ioBroker hilt da nur, ggfs. Alias zu setzten.

**Comment by tp1de** [comment]
Mathias ich bin dabei den Adapter narrensicherer zu machen. Es gibt aktuell viele kleinere Anpassungen. Ich habe bei den Dallas Sensoren einen Parameter zugefügt, mit dem das alte Format genutzt werden kann. V1.34.0

**Comment by MatzeFro** [comment]
Hallo Thomas, ja das funktioniert - ich werde aber auf das "neue" Format Wechsel. 
Ich habe aber nicht mehr die Version v3.5.1 getestet. bleibe bei der neuen. oder soll ich für dich etwas mit 3.5.1 testen?
