### ISSUE TITLE
Please fix issues reported by adapter checker

### ISSUE THREAD

**Issue by mcm1957** [tp1de/ioBroker.ems-esp#26]
👀 [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
 👀 [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)

**Comment by tp1de** [comment]
I do not understand the warnings. Translation is there ..... s owhy do I get warnings?

**Comment by mcm1957** [comment]
uk translation is missing for common.title.lang and common.desc

I agree that the text could be more informative.

**Comment by tp1de** [comment]
Found it  ... thanks

**Comment by tp1de** [comment]
done
