### ISSUE TITLE
Warnung nach Update von V1.30.0 auf V2.1.0

### ISSUE THREAD

**Issue by IOGogo** [tp1de/ioBroker.ems-esp#27]
Nach dem Update auf v 2.1.0 wird nach jeder Aktualisierung folgende Warnung im Iobroker Protokoll gemeldet:

**Der für „ems-esp.0.heatingCircuits.hc2.fastHeatupFactor“ festzulegende Statuswert hat den Wert „0“, der kleiner als min. „1“ ist.**
Diese Meldung kommt für hc1 und hc2

**Comment by tp1de** [comment]
Ich habe auch ab und zu diese Meldungen ... bin am überlegen wieso?
Bei v1.30 gab es die nicht? Habe an der Logik eigentlich nichts geändert.

Tritt diese Meldung nur sporadisch auf und bei jedem Lese-Durchlauf?

**Comment by tp1de** [comment]
Die min/max-Werte kommen per API vom ems-esp Gateway. Diese Werte kannst Du auch in den Settings/Customizations ändern, wenn bei Dir  andere Grenzen gelten.

**Comment by IOGogo** [comment]
Die Meldung kommt ca. alle 5 Minuten  beim  Lesevorgang .GrußHendrik 
-------- Ursprüngliche Nachricht --------Von: Thomas ***@***.***> Datum: 08.08.23  11:03  (GMT+01:00) An: "tp1de/ioBroker.ems-esp" ***@***.***> Cc: IOGogo ***@***.***>, Author ***@***.***> Betreff: Re: [tp1de/ioBroker.ems-esp] Warnung nach Update von V1.30.0 auf
  V2.1.0 (Issue #27) 
Ich habe auch ab und zu diese Meldungen ... bin am überlegen wieso?
Bei v1.30 gab es die nicht? Habe an der Logik eigentlich nichts geändert.
Tritt diese Meldung nur sporadisch auf und bei jedem Lese-Durchlauf?

**Comment by tp1de** [comment]
Welche ems-esp Firmware-Version benutzt Du? Bei mir sind die Min/Max-Werte auf 0/100 gesetzt.

**Comment by IOGogo** [comment]
Beim Buderus App wird die Version 3.9.2 angezeigt. GrußHendrik
-------- Ursprüngliche Nachricht --------Von: Thomas ***@***.***> Datum: 08.08.23  11:17  (GMT+01:00) An: "tp1de/ioBroker.ems-esp" ***@***.***> Cc: IOGogo ***@***.***>, Author ***@***.***> Betreff: Re: [tp1de/ioBroker.ems-esp] Warnung nach Update von V1.30.0 auf
  V2.1.0 (Issue #27) 
Welche ems-esp Firmware-Version benutzt Du? Bei mir sind die Min/Max-Werte auf 0/100 gesetzt.

**Comment by tp1de** [comment]
Hmmm ... ich dachte der Fehler tritt beim ems-esp Gateway auf. Aber bei Dir beim km200 (Buderus) Gateway. 

Auch dort habe ich bei der Logik nichts geändert ... die Warnmeldung kommt vom ioBroker System, wenn Werte außerhalb des erlaubten Wertebereiches gesetzt werden. Der Wertebereich kommt von der Buderus API - die Werte auch. 
Ich muss mal schauen, ob ich ggfs. alle Lesefehler (http get) richtig abfange.

**Comment by IOGogo** [comment]
Okay, und sorry für die Verwirrung…

Was sonderlich ist, dass ohne Veränderung nach dem Update auf V2.2.0 plötzlich auftritt.

Danke 

Gruß

Hendrik 

 

 

 

Von: Thomas ***@***.***> 
Gesendet: Dienstag, 8. August 2023 12:54
An: tp1de/ioBroker.ems-esp ***@***.***>
Cc: IOGogo ***@***.***>; Author ***@***.***>
Betreff: Re: [tp1de/ioBroker.ems-esp] Warnung nach Update von V1.30.0 auf V2.1.0 (Issue #27)

 

Hmmm ... ich dachte der Fehler tritt beim ems-esp Gateway auf. Aber bei Dir beim km200 (Buderus) Gateway.

Auch dort habe ich bei der Logik nichts geändert ... die Warnmeldung kommt vom ioBroker System, wenn Werte außerhalb des erlaubten Wertebereiches gesetzt werden. Der Wertebereich kommt von der Buderus API - die Werte auch.
Ich muss mal schauen, ob ich ggfs. alle Lesefehler (http get) richtig abfange.

**Comment by tp1de** [comment]
> Was sonderlich ist, dass ohne Veränderung nach dem Update auf V2.2.0 plötzlich auftritt.

Nein, ich gehe davon aus, dass dies schon vorher da war aber keine Warnung auslöste. Ich habe das ioBroker Grundsystem im Adapter auf den aktuellen Stand gebracht .... daher die Warnungen. Ich habe die aktuell 1-2 Mal am Tag. 

Ich überlege, Werte außerhalb des erlaubten Wertebereiches herauszufiltern und nicht zu schreiben.
Das hat aber auch Nachteile.

**Comment by IOGogo** [comment]
Okay dankeGrußHendrik 
-------- Ursprüngliche Nachricht --------Von: Thomas ***@***.***> Datum: 08.08.23  13:20  (GMT+01:00) An: "tp1de/ioBroker.ems-esp" ***@***.***> Cc: IOGogo ***@***.***>, Author ***@***.***> Betreff: Re: [tp1de/ioBroker.ems-esp] Warnung nach Update von V1.30.0 auf
  V2.1.0 (Issue #27) 

Was sonderlich ist, dass ohne Veränderung nach dem Update auf V2.2.0 plötzlich auftritt.

Nein, ich gehe davon aus, dass dies schon vorher da war aber keine Warnung auslöste. Ich habe das ioBroker Grundsystem im Adapter auf den aktuellen Stand gebracht .... daher die Warnungen. Ich habe die aktuell 1-2 Mal am Tag.
Ich überlege, Werte außerhalb des erlaubten Wertebereiches herauszufiltern und nicht zu schreiben.
Das hat aber auch Nachteile.

**Comment by tp1de** [comment]
Ich habe im Github eine Version mit der Werteabfrage. Wenn Du willst, dann kannst Du diese mal testen.

**Comment by IOGogo** [comment]
Okay  melde mich dann bei Dir GrußHendrik
-------- Ursprüngliche Nachricht --------Von: Thomas ***@***.***> Datum: 08.08.23  15:15  (GMT+01:00) An: "tp1de/ioBroker.ems-esp" ***@***.***> Cc: IOGogo ***@***.***>, Author ***@***.***> Betreff: Re: [tp1de/ioBroker.ems-esp] Warnung nach Update von V1.30.0 auf
  V2.1.0 (Issue #27) 
Ich habe im Github eine Version mit der Werteabfrage. Wenn Du willst, dann kannst Du diese mal testen.

**Comment by IOGogo** [comment]
Kannst Du mir die Versionsbezeichnung mit der Wertabfrage, die Du auf Github abgelegt hast, mitteilen?

Danke 

 

 

 

Von: Thomas ***@***.***> 
Gesendet: Dienstag, 8. August 2023 15:15
An: tp1de/ioBroker.ems-esp ***@***.***>
Cc: IOGogo ***@***.***>; Author ***@***.***>
Betreff: Re: [tp1de/ioBroker.ems-esp] Warnung nach Update von V1.30.0 auf V2.1.0 (Issue #27)

 

Ich habe im Github eine Version mit der Werteabfrage. Wenn Du willst, dann kannst Du diese mal testen.

**Comment by xx-94** [comment]
Hallo, ich habe die gleiche Warnmeldung bei meiner KM200. gibt es schon eine Lösung? 
oder kann ich hier die Werte wo einstellen?
State value to set for "ems-esp.0.heatingCircuits.hc2.fastHeatupFactor" has value "0" less than min "1"

Danke

**Comment by tp1de** [comment]
Ich habe seid gestern eine aktualisierte Version im GH. Kann über Adapter Installation über GH installiert werden. Expertenmodus einschalten. Hat aber noch keine neue Versionsnummer.

**Comment by tp1de** [comment]
Welchen Wert zeigt denn Eure Anlage beim Einstellen des Schnellaufheizungs-Faktor an? Gibt es diesen Parameter überhaupt?

**Comment by xx-94** [comment]
Hallo, werde ich gleich Testen 
ich habe mal ein Bild angehängt mit den Wert der aktuell auslesen wird.

<img width="1243" alt="Bildschirmfoto 2023-08-09 um 08 09 58" src="https://github.com/tp1de/ioBroker.ems-esp/assets/82840284/85a1f2d2-351b-43b4-b99c-cf551b9232df">

**Comment by tp1de** [comment]
Ja die km200 API gibt einen Wertebereich von 1 bis 100 vor aber einen aktuellen Wert von 0. Das ist inkonsistennt. Setzt den Wert mal auf 1 mit dem Objektbrowser (acknowleded =  false). Wird der Wert akzeptiert?

**Comment by tp1de** [comment]
Mich interessiert aber, ob es diesen Schnellaufheizungs-Faktor bei Euch in der Anlagenregelung überhaupt gibt?

**Comment by Bogie11** [comment]
Gleien Fehlermeldungen bei km200 - seit Update
Schnellaufheizungs-Faktor? Sagt mir nichts

![Fehler](https://github.com/tp1de/ioBroker.ems-esp/assets/98660784/f38d9d18-eaee-4471-ab88-85b4bcad9e8c)

**Comment by xx-94** [comment]
> Ja die km200 API gibt einen Wertebereich von 1 bis 100 vor aber einen aktuellen Wert von 0. Das ist inkonsistennt. Setzt den Wert mal auf 1 mit dem Objektbrowser (acknowleded = false). Wird der Wert akzeptiert?

habe denn Wert auf 1 gesetzt wird aber wieder auf 0 zurückgesetzt.

**Comment by xx-94** [comment]
> Mich interessiert aber, ob es diesen Schnellaufheizungs-Faktor bei Euch in der Anlagenregelung überhaupt gibt?

ich habe diesen noch nicht gefunden.

**Comment by tp1de** [comment]
@Bogie11  

> Gleiche Fehlermeldungen bei km200 - seit Update
> Schnellaufheizungs-Faktor? Sagt mir nichts

Hast Du von GH installiert und dann die Instanz neu gestartet?

**Comment by tp1de** [comment]
@xx-94 

> habe denn Wert auf 1 gesetzt wird aber wieder auf 0 zurückgesetzt.

Mit acknowledged = false ? Wenn ja, dann ist dieser Parameter ggfs. nicht aktiv.

**Comment by Bogie11** [comment]
> @Bogie11
> 
> > Gleiche Fehlermeldungen bei km200 - seit Update
> > Schnellaufheizungs-Faktor? Sagt mir nichts
> 
> Hast Du von GH installiert und dann die Instanz neu gestartet?

Nein, habe ich nicht. Nur Update per iobroker

**Comment by Bogie11** [comment]
> 
sieht nicht aktiv aus: letzte Änderung in 2022

![Fehler1](https://github.com/tp1de/ioBroker.ems-esp/assets/98660784/990b2491-d5e0-40e1-b2e1-fb8ea9a54b16)

**Comment by tp1de** [comment]
Bei mir ist die km200 Gateway-Firmware zuletzt im August 2022 aktualisiert worden. 
Dabei sind einige Datenpunkte weggefallen ... auch der fastHeatup für den hc2 (Fußboden-Heizkreis)
Jetzt habe ich die automatische Aktualisierung ausgeschaltet.
Ich glaube 0 ist als "deaktiviert" zu interpretieren. Probiert aber noch 2 bis 3 Mal den Wert auf 1 zu setzen. (steht etwas im Log?)

**Comment by xx-94** [comment]
bei mir ist es auch mit hc1. evtl. könntest die abfrage so einbauen das man es ggf. wieder aktivieren kann.

**Comment by tp1de** [comment]
Aktueller Stand:

Es gibt beim km200 Gateway / API einige wenige States, welche einen erlaubten Wertebereich (Min / Max) haben und zusätzlich diskrete States wie Z.B. "off = 0 " oder "na = -1" . Aktuell kenne ich zwei States: fastHeatupFactor und temporaryRoomSetpoint.

Für diese Kombination habe ich noch keine Lösung, wie ich dieses im ioBroker  abbilden kann.
Ich habe jetzt den ems-esp Adapter so geändert, dass die erlaubten Min / Max Werte entsprechend geändert werden.
Falls dennoch Werte außerhalb des Wertebereiches kommen sollten, so erzeuge ich eine Info-Message im Log.

Es wäre gut, wenn Ihr diese Version im GH testen könntet, bevor ich eine neue Version erstelle.
(Ich bin aber noch auf der Suche, ob es eine andere Möglichkeit im ioBroker gibt.)

**Comment by tp1de** [comment]
Es gibt jetzt Version 2.2.0 - damit sollten die Meldungen weg sein.

**Comment by Bogie11** [comment]
Meldungen sind bei mir nach dem Update nicht mehr vorhanden.
Danke :-)

**Comment by tp1de** [comment]
@xx-94 @IOGogo  Sind die Meldungen auch bei Euch weg mit der Version 2.2.0? 
Falls ja, kann dieses Issue geschlossen werden.

**Comment by xx-94** [comment]
Hallo, ja sind auch weg. funktioniert jetzt ohne Probleme. 
Danke

**Comment by IOGogo** [comment]
Alles okay .. DankeGrußHendrik 
-------- Ursprüngliche Nachricht --------Von: Thomas ***@***.***> Datum: 10.08.23  18:05  (GMT+01:00) An: "tp1de/ioBroker.ems-esp" ***@***.***> Cc: IOGogo ***@***.***>, Mention ***@***.***> Betreff: Re: [tp1de/ioBroker.ems-esp] Warnung nach Update von V1.30.0 auf
  V2.1.0 (Issue #27) 
@xx-94 @IOGogo  Sind die Meldungen auch bei Euch weg mit der Version 2.2.0?
Falls ja, kann dieses Issue geschlossen werden.
