### ISSUE TITLE
error reading KM200 gateway information (wrong passwords please re-enter) - stop km200 read

### ISSUE THREAD

**Issue by martin-ef** [tp1de/ioBroker.ems-esp#28]
Hello, 

I'm trying to use the km200-part for my Buderus gateway. I checked the IP, used the gateway pw and the private pw which I use for the Buderus MyDevice App (which works perfectly fine). For the gateway pw I used the 16 digits with our without the dash.

The instance mouseover tells me its connected but when I check in objects > controls > active it's not. 

Can someone please help me?

thanx, Martin

**Comment by tp1de** [comment]
Gw password is with dashes. 1:1 as printed on the sticker

**Comment by tp1de** [comment]
Does it work now?

**Comment by martin-ef** [comment]
sorry - I didn't get the first answer so I'm kinda late answering. 

I just tried again, but in the protocol it always says "wrong password". When I check in objects - there are still most of the fields filled with data - I just don't know wether they are old or new. Ems-esp>0>controls>active is set to false :(

**Comment by martin-ef** [comment]
sorry - I didn't mention, that I have version 2.1.0 installed. I just checked iobroker and switched to beta repository. It then tells me that the newest version is 1.30.0 !

When trying to install from GitHub it tells me: 
$ iobroker url tp1de/ioBroker.ems-esp --host ioBroker --debug
install tp1de/ioBroker.ems-esp
NPM version: 8.19.3Installing tp1de/ioBroker.ems-esp... (System call)
host.ioBroker Cannot install tp1de/ioBroker.ems-esp: 128
ERROR: Process exited with code 25

so how can I upgrade to 2.2.0?

**Comment by tp1de** [comment]
Something wrong with your iobroker repositories. But the main km200 code hasn't changed since a couple of months. 2.2.0 is in the stable repo since today.

When the message "wrong password " is shown, then one of the passwords is wrong. The combination is needed for encryption. 

Was it working before? What has changed?

**Comment by tp1de** [comment]
Do not use GH to install. It is a testing version!

**Comment by martin-ef** [comment]
So, I removed the app, restarted iobroker and re-installed ems-esp (still v. 2.1.0 is the most recent one).

The only difference I noticed: Before I defined the IP-address without "http:". Reinstalling the app it showed me to input the "http:" as well.

So I'm not sure whether the old instance was corrupted or the "http:"error was the problem solver. Anyhow - it works :)

**Comment by martin-ef** [comment]
I'm using nodes v. 16.19.1

**Comment by tp1de** [comment]
The IP-address works with and without "http://" prefix. Your ioBroker repositories does not seem to be updated automatically.
Check your installation and please update to version 2.2.0. (use manual update from adapter menu if 2.2.0 is not shown)
