### ISSUE TITLE
Dauerhafte Warneineinträge im Protokoll

### ISSUE THREAD

**Issue by Cortexlentis** [tp1de/ioBroker.ems-esp#29]
**Describe the bug**  
Ich erhalte im Protokoll wiederkehrende Warnreinträge (siehe Screenshot).

**Releated to gateway and adapter configuration**
B KM200
C 
D 

**Expected behavior**  
Der Adapter funktioniert super, aber das Protokoll nicht mit Warneinträgen geflutet zu bekommen wäre nett.

**Additional context**  
-

![grafik](https://github.com/tp1de/ioBroker.ems-esp/assets/114985246/a1cc0c75-9722-4172-9bfe-ee64c5e68b08)

**Comment by tp1de** [comment]
V2.2.0 installiert?

**Comment by Cortexlentis** [comment]
Habe die Version über den Expertenmodus installiert, da diese nicht offiziel released ist. 
Das Problem ist jetzt jedenfalls weg. Danke.
