### ISSUE TITLE
Edit KM200.csv 

### ISSUE THREAD

**Issue by sello89** [tp1de/ioBroker.ems-esp#35]
The Adapter is working perfectly, but i want to edit the km200.csv file because i get lot error because there are to many fields in dont need. 

how i can do that ??? 

I think there are many people out there with the same problem as me.

**Comment by tp1de** [comment]
What errors are you talking about?

**Comment by sello89** [comment]
![IMG_5181](https://github.com/tp1de/ioBroker.ems-esp/assets/49493020/b43a3898-8009-45fa-93b3-1ecff8954548)

error is maybe not the correct word… iobroker tells me that many values are out of range or something likewise … because the plugin can‘t get the values from my heating system … thats why i want to adjust the KM200.csv … to only get the datapoints in need

**Comment by tp1de** [comment]
The api reads the definitions and values that do not fit in your case. Run the instance that only warnings are written to log. Please use forum for questions, not github.
You can edit the csv file in different ways. E.g. use winscp for windows.
