### ISSUE TITLE
History DB Issue with KM200 Monthly Recordings

### ISSUE THREAD

**Issue by Track4123** [tp1de/ioBroker.ems-esp#37]
Hi. Initially recording of the consumptions was enabled via an influxdb.
For different reasons I want to move to the history adapter. Doing so it works for the hourly and daily items, 
however, data are not up to date for the the monthly items . Turning back to the influxdb monthly data are Ok.
On below, data are not OK anymore since August 2023

![image](https://github.com/tp1de/ioBroker.ems-esp/assets/144127021/caffb87d-a519-43d5-8d83-50c849f7c69f)

Any clue?
thx!

**Comment by tp1de** [comment]
Which adapter version?

**Comment by Track4123** [comment]
v2.5.1

**Comment by Track4123** [comment]
as I see it, yes... just switch back to influxdb and data are there und updated...
![image](https://github.com/tp1de/ioBroker.ems-esp/assets/144127021/90a574fb-5af0-45f2-b65c-1555376ebad1)

Also data in arrays, if it's this what you mean
[1013.4,851.1,673.1,497.4,419,1724.3,3022.4,4094.2,3957,4240.1,4175.5,3662.7,1757.1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]

**Comment by Track4123** [comment]
and here 
![image](https://github.com/tp1de/ioBroker.ems-esp/assets/144127021/bdcfc8ab-dd28-44e6-90f7-4ad2058e3c81)

**Comment by tp1de** [comment]
My findings so far:

- the last version of history adapter (3.0.0) behaves different then before (2.2.6)
- the actual version of admin adapter (6.10.8) .does not allow to delete/change records in object browser anymore
  version 6.10.5 is working fine for history and SQL
- within adapter code overwriting existing values (in your case existing 0 values) is not working anymore as before.

I will try to adjust the coding for history and InfluxDB.
Since I can't delete any records for InfluxDB V2,  I plan to not support InfluxDB in the future anymore.
I strongly recommend to use mySQL / MariaDB.

I will inform, when a new version can be tested. (in a couple of hours)

**Comment by tp1de** [comment]
I updated the version to 2.5.2 - should be available within ioBroker repo soon - or you install fro Github.
Please report if it is working for you as well.

I included warnings within log if InfluxDB V2 is used. I will not support in future versions anymore.

**Comment by Track4123** [comment]
after updating it works now, great! I will monitor the next days if any other topic, else I will close .
btw, there is no option to get a prediction of the consumption of current year? (based on current cumulated values)?

**Comment by tp1de** [comment]
> btw, there is no option to get a prediction of the consumption of current year? (based on current cumulated values)?

There are last 12 month energy consumption states: last12m for dhw,  ch and total. What else?

**Comment by Track4123** [comment]
well, it would be good to have an "outlook, prediction, forcast" for the total current year, example, 
lets say I have consumption till september and I want to predict my consumption till End of December, like a Forecast for 2023,
just an idea, else I will see if I can do something with Statistics adapter

**Comment by Track4123** [comment]
Hi, me again! Montly recording is working now. As you triggered me on the last 12 month ;-) I see the  figures do not add up?Sum of months is 28772 while 29074 are shown in the last 12 month? It triggered me because data where not changing day by day.  This is now for the total figure, but subtotals for the CH and DHW behave the same-
Still something related to the original problem with the monthly figures on the history adapter?
![image](https://github.com/tp1de/ioBroker.ems-esp/assets/144127021/2a045eea-091b-4d5d-8693-8fa7b240301f)

**Comment by tp1de** [comment]
Sum is without aktualisiert month
