### ISSUE TITLE
Adapter crash v2.6.0

### ISSUE THREAD

**Issue by mbhomie007** [tp1de/ioBroker.ems-esp#40]
Adapter crash v2.6.0 since update to V2.6.0

![image](https://github.com/tp1de/ioBroker.ems-esp/assets/64688879/f48353f3-4e3d-45eb-8de7-e0ffbf93cf8a)

![image](https://github.com/tp1de/ioBroker.ems-esp/assets/64688879/23d24c93-2d45-4280-9c61-1c18998251bf)

![image](https://github.com/tp1de/ioBroker.ems-esp/assets/64688879/c01ec59c-d47c-45b3-8eb9-2e57259142eb)

**Comment by tp1de** [comment]
Do you start the Adapter with parameter to delete states?

**Comment by mbhomie007** [comment]
No, I don't.

I will test the new version.

**Comment by mbhomie007** [comment]
No problem anymore with the new version.
