### ISSUE TITLE
km200

### ISSUE THREAD

**Issue by rkocri** [tp1de/ioBroker.ems-esp#41]
I have a Buderus oil burner connected to an underfloor heating system. For this, I am using the WM10 mixing module to operate a buffer storage tank as a hydraulic separator. 
Unfortunately, I can't find the flow temperature of the heating circuit or the temperature inside the separator (in my case, the buffer storage tank) in the outputs I get from my KM200.
Am I looking in the wrong place, or are the details from the mixing module not available?

**Comment by tp1de** [comment]
Km200 does not contain hardware info. No info is available for mixers.
