### ISSUE TITLE
KM200: Axios put: Errormeldung bei jeder schreibbaren Variable

### ISSUE THREAD

**Issue by YoshiEd** [tp1de/ioBroker.ems-esp#42]
A clear and concise description of what the bug is:

Wenn eine Variable im Iobroker geschrieben werden soll (testweise direkt aus dem Objects-Baum), kommt immer der gleiche Typ Fehlermeldung 404. Beispiel aus dem Log

2023-12-14 19:08:14.396 | warn | KM200 http write error undefined:heatingCircuits.hc1.temperatureLevels.comfort2
2023-12-14 19:08:14.396 | error | axios put: heatingCircuits.hc1.temperatureLevels.comfort2  AxiosError: Request failed with status code 404
2023-12-14 19:08:14.292 | info | KM200 write change: ems-esp.0.heatingCircuits.hc1.temperatureLevels.comfort2: 21

Dies passiert bei allen Variablen die ich versuche zu schreiben. Der Wert wird auch nicht in die Wärmepumpe übertragen.

B Which version of the ems-esp adapter are you using? 
V2.6.2

C is this bug related to the ems-esp or km200 gateway? (which gateway hardware are you using?)
MB LAN gateway in Bosch Erdwärmepumpe CS7000iLW mit iCOM_Low_NSCv1 MB LAN

D please descripe software versions of the ems-esp firmware and/or km200 gateway 
SW-Version 04.08 laut Display

E please post screenshot(s) of the adapter config
![grafik](https://github.com/tp1de/ioBroker.ems-esp/assets/75631191/eab8a08f-2066-4c16-a1ad-a3f227d650e6)
![grafik](https://github.com/tp1de/ioBroker.ems-esp/assets/75631191/13c15181-4a3e-4ba8-94c3-7aebaa5e173d)
![grafik](https://github.com/tp1de/ioBroker.ems-esp/assets/75631191/ce1f2601-76cf-4990-a8f6-9f36123da73c)

**Expected behavior**  

Wenn eine Variable direkt im Objects-Baum beschrieben wird, sollte der Wert auch in die WP übertragen werden. :-)

Vielen Dank!

**Comment by tp1de** [comment]
Ich kann das erst einmal nicht nachvollziehen.  Bitte mal die Version  2.5.2 installieren. Tritt der Fehler noch auf?

**Comment by YoshiEd** [comment]
Nach dem Downgrade auf 2.5.2 tritt der Fehler immer noch identisch auf. 
Sollte ich noch weiter downgraden?

Ich scheine nicht der einzige mit dem Fehlercode 404  zu sein: 
https://forum.iobroker.net/topic/69081/problem-mit-ems-esp?_=1702583787984&lang=de
Dort werden aber scheinbar auch keine Werte mehr gelesen.

**Comment by tp1de** [comment]
Der Unterschied von 2.6.2 und 2.5.2 ist das 2.5.2 axios post verwendet. Es gab einen User wo das nnut mit axios put funktionierte.
Das ist dann ab 2.5.3 implementiert.

Du kannst die Version 2.4.1 mal ausprobieren. Dort ist noch der "alte" request Befehl verwendet. Request ist aber abgekündigt.

**Comment by tp1de** [comment]
Ich habe im Github mal eine neue Adapterversion mit aktuellen Dependencies .. und damit auch der aktuellsten Axios Version hochgeladen. Diese kannst du auch mal ausprobieren, obwohl ich mir nicht vorstellen kann, dass es daran liegt.

**Comment by YoshiEd** [comment]
> Du kannst die Version 2.4.1 mal ausprobieren. Dort ist noch der "alte" request Befehl verwendet. Request ist aber abgekündigt.

2.4.1 funktioniert auch nicht, Die Fehlermeldung lautet jetzt leicht anders (logisch, gibt ja noch kein axios):

 2023-12-14 22:39:15.427 | warn | KM200 http write error 404:heatingCircuits.hc1.temporaryRoomSetpoint
 2023-12-14 22:39:15.320 | info | KM200 write change: ems-esp.0.heatingCircuits.hc1.temporaryRoomSetpoint: 21

**Comment by tp1de** [comment]
Dann kann es eigentlich daran liegen, dass das LAN Gateway keine Schreibbefehle im lokalen Netzwerk zulässt. Ich weiss auch nicht mehr weiter .... außer der Empfehlung ggfs. das Ems-Esp Gateway zu kaufen  ....

**Comment by tp1de** [comment]
Wie sehen denn die Objekt-Attribute aus?
![grafik](https://github.com/tp1de/ioBroker.ems-esp/assets/36480251/7a0819de-bab0-40bb-a5c1-aef8784d6b82)

**Comment by YoshiEd** [comment]
Was bei mir fehlt ist der letzte Block:
"ac1"
....
Der Rest ist identisch.
![grafik](https://github.com/tp1de/ioBroker.ems-esp/assets/75631191/d4c8abc6-b70e-4ec9-85d6-1fbafbfabd27)
![grafik](https://github.com/tp1de/ioBroker.ems-esp/assets/75631191/4eb68f36-5a48-424a-9b69-c34db5a49c5c)

**Comment by tp1de** [comment]
Welche node js version benutzt du und welches OS?

**Comment by YoshiEd** [comment]
Ich benutze Ubuntu 22.04.3 LTS auf einem DELL Optiplex 3050 mit 
Node.js: v18.17.1 
NPM Version 9.6.7
js-controller 5.0.16

    Plattform: linux
    Betriebssystem: linux
    Architektur: x64
    CPUs: 4
    Geschwindigkeit: 900 MHz
    Modell: Intel(R) Core(TM) i5-6500T CPU @ 2.50GHz
    RAM: 7.6 GB
    System-Betriebszeit: 2 T. 20:52:45
    Node.js: v18.17.1
    NPM: 9.6.7
    Adapter-Anzahl: 517
    Freier Festplattenspeicher: 216.2 GB
    Aktive Instanzen: 20
    Pfad: /opt/iobroker/

**Comment by tp1de** [comment]
Ich habe keine Idee mehr woran das liegt. Die State Definition ist richtig und lässt Updates zu. Nodejs und Ubuntu sind auch richtig. 

Sowohl request wie auch axios put / post funktionieren nicht.
D.h. das Gateway blockt diese http Schreibbefehle mit Code 404 ab.

**Comment by YoshiEd** [comment]
Ich habe heute morgen die WP einmal komplett ausgeschaltet (400V AC ) und nach einer Minute warten wieder eingeschaltet. Seitdem konnte ich alle Variablen schreiben und sie werden auch von der WP übernommen. 
Es tauchen auch keine Fehlermeldungen im Log mehr auf.
Vielen, vielen Dank für deine Unterstützung, auch wenn es letztendlich nur ein "Reboot tut gut" war und nichts mit dem Adapter selber zu tun hatte.

**Comment by tp1de** [comment]
Gut zu wissen ... auch ich musste in den letzten 3 Jahren 5 Mal meine Anlage neu starten - d.h. stromlos machen.
Dann hat der Adapter aber auch keine neuen Werte mehr gelesen.
