### ISSUE TITLE
State value to set for "ems-esp.0.dhwCircuits.dhw1.temperatureLevels.high" has value "48" greater than max "46"

### ISSUE THREAD

**Issue by EvilEls** [tp1de/ioBroker.ems-esp#43]
Hi!
I'm getting warning:
`State value to set for "ems-esp.0.dhwCircuits.dhw1.temperatureLevels.high" has value "48" greater than max "46"`

Could you please raise max value or remove min/max for dhw temp levels?

**Comment by tp1de** [comment]
The min/max values are set by the gateway api and not by the adapter. 
Within EMS-ESP Gateway you can set min/max within customizations. 
For BOSCH Group Gateways these values are set by the firmware and for some values within the thermostat settings.

The warning is raised by ioBroker base system. If you do not want warnings to be displayed set the adapter instance loglevel to error.
