### ISSUE TITLE
Daten werden nicht mit Version 2.6.3 aktualisiert. KM200

### ISSUE THREAD

**Issue by IOGogo** [tp1de/ioBroker.ems-esp#47]
"Daten werden mit der oben genannten Version nicht aktuallsiert."

Systemdaten:
Plattform: docker (official image - v9.0.1)
Betriebssystem: linux
Architektur: x64
CPUs: 2
Geschwindigkeit: 2001 MHz
Modell: Intel(R) Celeron(R) CPU J3355 @ 2.00GHz
RAM: 9.5 GB
System-Betriebszeit: 220 T. 11:06:26
Node.js: v18.19.0
time: 1706788795180
timeOffset: -60
NPM: 10.2.3
Adapter-Anzahl: 527
Datenträgergröße: 3572.6 GB
Freier Festplattenspeicher: 3198.3 GB
Aktive Instanzen: 28
Pfad: /opt/iobroker/
Betriebszeit: 05:28:16
aktiv:

Buderus gb212 Km200

**Comment by tp1de** [comment]
???? Was steht im Log?

**Comment by tp1de** [comment]
Schau mal, ob sich dein Gateway aufgehängt hat. 
Brenner / Gateway ausschalten, etwas warten und wieder einschalten ....

**Comment by IOGogo** [comment]
Im Log wird keine Fehlermeldung angezeigt.  
Wenn ich auf die letzte Version vor der Aktualisierung gehe funktioniert alles

**Comment by tp1de** [comment]
> Wenn ich auf die letzte Version vor der Aktualisierung gehe funktioniert alles

Das ist merkwürdig und kann ich nicht nachvollziehen - welche Version funktioniert denn bei dir?

**Comment by IOGogo** [comment]
Die Version 2.6.2 funktioniert einwandfrei.

**Comment by IOGogo** [comment]
Ja , ich versuche beide Möglichkeiten und gebe Rückmeldung.. Allerdings erst morgen Früh..

**Comment by IOGogo** [comment]
Brenner / Gateway ausschalten hat funktioniert. Was ich aber nicht verstehen kann ist, dass es bei der Version 2.6.2 ohne Neustart funktioniert hat. Trotzdem danke für die schnelle Unterstützung.

**Comment by tp1de** [comment]
Ja es ist bekannt,  das das km200 sich immer mal aufhängt bzw. keine Daten mehr bereitstellt. Diese Gateways liefert Bosch / Buderus nicht mehr. 

Die neuen MX300 unterstützen LAN Zugriff nicht mehr.
Dann bleibt nur das wesentlich bessere ems-esp Gateway.
