### ISSUE TITLE
Unusal files at adapter root - please check

### ISSUE THREAD

**Issue by mcm1957** [tp1de/ioBroker.ems-esp#49]
The following files seem to be misplaced at adapter root directoy:

index_m.html
words.js

Thea are normally located at admin directory (and they are there too)

----

Please check whether driectories:test is really desired at package.json. normally the test directory is NOZT delivred to customer systems
https://github.com/tp1de/ioBroker.ems-esp/blob/db32f2e8f0a7a5ee9c9c50a5e974197aa18db779/package.json#L64

**Comment by tp1de** [comment]
Thanks for input ... it's now corrected
