### ISSUE TITLE
update ioBroker.ems-esp failed

### ISSUE THREAD

**Issue by latte-macchiato** [tp1de/ioBroker.ems-esp#52]
Update to available Version 3.0.3:
The update is going through, but a 404 appears in the Instances section.

with... ioBroker Update -i

I receive the following message

Used repository: stable
Cannot read or parse /opt/iobroker/node_modules/@iobroker/js-controller-common/build/lib/common/.. /node_modules/iobroker.ems-esp/io-package.json: /opt/iobroker/node_modules/iobroker.ems-esp/package.json: Unexpected end of JSON input
Cannot read or parse /opt/iobroker/node_modules/@iobroker/js-controller-common/build/lib/common/.. /node_mod

**Comment by tp1de** [comment]
Which node Version are you using?

**Comment by latte-macchiato** [comment]
Node.js: v18.19.1
NPM: 10.2.4
IOBROKER: 5.0.19
ADMIN: 6.13.16

**Comment by latte-macchiato** [comment]
After updating node.js v20.12.1 and npm it works.
It was nessassery to use the command: iobroker -fix
