### ISSUE TITLE
SyntaxError: Unexpected token � in JSON at position 0

### ISSUE THREAD

**Issue by Cortexlentis** [tp1de/ioBroker.ems-esp#53]
After Updating the Buanet Iobroker Image in the Docker to the latest Version (Node.js: v18.20.1 / NPM: 10.5.1 / IOB: v6.13.16) for the update of the ems-esp to Version 3.03 i get a red protocol response by using the km200 gateway:

km200 decrypt: http://192.168.0.225 - SyntaxError: Unexpected token � in JSON at position 0

Excepting this entry the Adapter works fine an i get the data from the km100.
No additional entrys in the configuration excepting ip adress an password(s).

Is this a problem that I can fix by myself or is it a failure in the adapter?

Thank you.

![Screenshot 2024-04-05 180326](https://github.com/tp1de/ioBroker.ems-esp/assets/114985246/4e3a3d14-c8e5-47d1-a275-859ead675141)

**Comment by tp1de** [comment]
The error indicates missing data for one field.

What has bee changed.

New docker Version. Does the previous adapter version giving the same error?
Is the error persistent for every adapter start?

**Comment by Cortexlentis** [comment]
the previous adapter does not come up with this error message.
it pops up every time you restart the adapter. also the iobroker was restarted - same thing.

**Comment by tp1de** [comment]
I added a second error message identifying the get request which gives this error message.
Could you please install the adapter version from Github and restart the adapter?
Please post the error messages ...

**Comment by Cortexlentis** [comment]
Sure...
![Screenshot 2024-04-06 212716](https://github.com/tp1de/ioBroker.ems-esp/assets/114985246/e6c4c7f9-d164-4afe-ad4d-308ec0f7bc9c)

**Comment by tp1de** [comment]
Thanks for your response. As far as I can see this http get request returns a trailing blank. I haven't seen this before.
I changed the code to remove this blank.
Could you give it a new try by installing again from Github?

**Comment by tp1de** [comment]
I can reproduce now on my heating system for the /gateway/firmware field.
I have to check if I just skip this error or if I can find a solution.

**Comment by tp1de** [comment]
The field /gateway/firmware contains binary data. All other fields a JSON data object.
I can not decode tis data - so I skip unreadable data now.

I hope it works with version 3.1.0. now.

**Comment by Cortexlentis** [comment]
Works fine, no unexpected protocol entry so far.
Thank you very much for the quick support!
![Screenshot 2024-04-07 154032](https://github.com/tp1de/ioBroker.ems-esp/assets/114985246/8de4de02-4954-4633-868d-1407d703032d)
