### ISSUE TITLE
Please readd tests for windows and mac

### ISSUE THREAD

**Issue by mcm1957** [tp1de/ioBroker.ems-esp#54]
Executing standard T´testing at ALL supported platforms is mandatory. Please reactivate the test.

**Comment by tp1de** [comment]
I reactivated the tests for all platforms. But actually the windows tests do not work. What shall I do?

https://github.com/tp1de/ioBroker.ems-esp/actions/runs/8721074711/job/23924010766

**Comment by mcm1957** [comment]
Please check forum and/or telegram channels for news regularly.

There was a problem caused by changes done by Microsoft. **Please update @iobroker/testing to 4.1.3. This should do the trick.**

**Comment by tp1de** [comment]
@mcm1957  Thanks for input ... it works now. 

But I have to admit that I am starting to get annoyed about the ioBroker adapter development environment.
For non-IT people it is too difficult to follow all necessary changes which has to be observed. (or I am getting too old now)
There should be one web-site where all these prerequisite can be followed easily to minimize the efforts.

**Comment by mcm1957** [comment]
Maybe you should consider subscribing to tegram (or discord) developer channel if not yet done.
Invites available at www.iobroker.dev.
