### ISSUE TITLE
Möglichkeit nur eingeblendete Gerätedaten zu übernehmen

### ISSUE THREAD

**Issue by mattreim** [tp1de/ioBroker.ems-esp#55]
Vielen Dank für diesen Adapter. 

Nach der Einrichtung/Anpassung meines neuen EMS-ESPs werden nun alle Geräteentitäten an den Adapter übergeben. 

![Anpassungen](https://github.com/tp1de/ioBroker.ems-esp/assets/80219712/00d59111-90d2-408b-bc94-5a3ea04ba80a)

Ich würde gerne nur die Daten aus dem Kontrollzentrum in dem Adapter/IoBroker verarbeiten. Vielen Dank

**Comment by tp1de** [comment]
Es gibt doch die Möglichkeit von MQTT / API auszuschließen. 
Funktioniert das nicht?

**Comment by mattreim** [comment]
Sorry, hat natürlich funktioniert. Danke für die Hilfe.
