### ISSUE TITLE
Einige Attribute besitzen die falschen Datetypen

### ISSUE THREAD

**Issue by mattreim** [tp1de/ioBroker.ems-esp#56]
Hallo,

nach der Einrichtung des Adapters erscheinen folgende Einträge im Log.

![EMS-ESP-Fehler2](https://github.com/tp1de/ioBroker.ems-esp/assets/80219712/8537c126-0a03-4834-a9bb-de26e7264f45)

Und über die Nacht geht es so weiter.

![EMS-ESP-Fehler](https://github.com/tp1de/ioBroker.ems-esp/assets/80219712/d7f1edb3-61f2-4673-8f72-aa53437deee7)

Vielen Dank im Voraus

**Comment by tp1de** [comment]
Github sollte nicht für Hilfestellungen verwendet werden. Dafür ist das Forum da.

Punkt 1: überprüfe im ems-esp custumizations die min und max Werte bzw. den aktuellen Wert. Ändere die Werte ggfs.

Punkt 2: kann ich nicht nachvollziehen. Stopp die Instanz,  lösche die Objektstruktur und starte neu.

**Comment by mattreim** [comment]
Punkt 1: Es sind alles Standardwerte die von der  Heizung kommen. Die  min/max Werte für "burnmaxpower" waren falsch vergeben, aber die anderen Werte sind alle Zeichenketten.

Fanwork:
![EMS-ESP](https://github.com/tp1de/ioBroker.ems-esp/assets/80219712/21dcba5e-666b-4a20-b1bd-aa71ffc7a45d)


Punkt 2: Wenn ich die Objektstruktur lösche und neu starte sieht es wie auf dem ersten Screenshot aus. Habe ich natürlich schon versucht.

**Comment by mattreim** [comment]
Hier noch eine frische Log-Datei:

[iobroker.2024-04-19.log](https://github.com/tp1de/ioBroker.ems-esp/files/15044867/iobroker.2024-04-19.log)

Nach dem löschen der Objektstruktur.

**Comment by tp1de** [comment]
Hast du in den ems-esp settings die Attribute nach Anleitung richtig gesetzt?

![image](https://github.com/tp1de/ioBroker.ems-esp/assets/36480251/ce6877c9-6ef9-4b9e-a049-78c9b837bcdf)

**Comment by mattreim** [comment]
Nein, es ist mein erster Adapter der mit Dateitypen ein Problem hat. Für die Übersichtlichkeit und Verarbeitung sind string/boolean schon besser.

**Comment by tp1de** [comment]
Um den Adapter zu verwenden musst du die Formatting Options so setzen wie beschrieben. (so wie alle anderen Anwender auch)
Der API-Output ist abhängig von der eingestellten Sprache,

Wozu habe ich die Doku geschrieben ?! Ich baue in der nächsten Version ein Check ein.
