### ISSUE TITLE
Die Instanzeinstellungen werden nicht richtig gespeichert.

### ISSUE THREAD

**Issue by mattreim** [tp1de/ioBroker.ems-esp#57]
Wenn man die Instanzeinstellungen öffnet und danach auf Abbrechen geht erscheint beim Wechsel des Reiters die folgende Meldung:

![Verwerfen](https://github.com/tp1de/ioBroker.ems-esp/assets/80219712/e2a43e18-d1f7-4982-a881-c42438e55051)

Instanzeinstellungen:
Soll:
![Soll](https://github.com/tp1de/ioBroker.ems-esp/assets/80219712/20cef162-7c6c-4f92-8fbe-16da3d0c85a1)

Ist:
![Ist](https://github.com/tp1de/ioBroker.ems-esp/assets/80219712/4774bcb2-42cb-457b-93f5-4671df0b0fcb)

**Comment by tp1de** [comment]
Kann ich nicht nachvollziehen. Hast die die aktuellste Admin Version?

**Comment by mattreim** [comment]
Es ist alles auf dem aktuellen Stand.

**Comment by mattreim** [comment]
Auch eine Neuinstallation bringt keine Verbesserung.

**Comment by tp1de** [comment]
Ich kann deinen Fehler nicht nachvollziehen.
Bitte beschreibe genau welche Schritte du unternimmst und was genau nicht funktioniert.

**Comment by mattreim** [comment]
Schritt 1:

![EMS-ESP](https://github.com/tp1de/ioBroker.ems-esp/assets/80219712/a219d2af-aa82-40a5-9325-2d7fcc6e1c7b)

Schritt 2: Ist/Soll siehe oben

**Comment by tp1de** [comment]
Diese Verhalten wird vom Admin-Adapter gesteuert nicht von meinem Adapter. Ich wüsste nicht was ich verändern sollte.

... übrigens die neueste ems-esp Firmware dev 3 funktioniert mit dem Adapter nicht richtig. Nicht installieren.

**Comment by mattreim** [comment]
Aber bei meinen anderen Adaptern funktioniert es.

**Comment by tp1de** [comment]
Danke für die bereitgestellte jsonConfig. 
Funktioniert soweit, aber mit einer speziellen Funktion bin ich überfordert:

bisher habe es index_m.html und index_m.js. In index_m.html sind die Tabs mit Eingabefeldern beschrieben. Diese hats Du in json übersetzt. Es fehlt nur der letzte Tab "advanced". Dieser spezielle "Expertenmodus für das ems-esp Gateway" wurde dynamisch angezeigt. Die Steuerung erfolgte im index_m.js script.
Ich bin aktuell überfragt, wie ich das in der jsonConfig hinbekomme.

**Comment by mattreim** [comment]
Ich schaue es mir nochmal an.

**Comment by mattreim** [comment]
Diese Meldungen scheinen keine [Fehler](https://forum.iobroker.net/topic/69570/logging-warnung-admin-0-ical-has-an-invalid-jsonconfig) von der jsonConfig zu sein.

**Comment by mattreim** [comment]
Sie werden [hier ](https://github.com/ioBroker/adapter-react-v5/issues) gesammelt und dann über den admin verteilt.

**Comment by tp1de** [comment]
Ja der admin adapter hat aktuell einige Probleme.
Mit der admin version 6.8.0 gibt es keine Warnmeldungen, mit latest stable 6.13.16 aber schon. Ebenso mit der aktuellen dev version.

So kann ich die aktuelle Version vom ems-esp adapter nicht freigeben. Die Warnmeldungen irritieren nur.

**Comment by tp1de** [comment]
Ich bin erst einmal zurück zur alten Version, um ein paar andere Änderungen einzupflegen (Meldungen vom adapter checker)

**Comment by tp1de** [comment]
Im GH gibt es eine Anpassung der jsonConfig mit "select". Funktioniert bei mir soweit. Bei dir auch?

**Comment by mattreim** [comment]
Ja, sehr gut und die Meldung ist auch weg. Da wollte er wohl "autocomplete" nicht.

**Comment by tp1de** [comment]
Ich habe gerade die jsonConfig Version released (v4.0.0). Ich musste noch eingies anpassen. Sowohl in der jsonConfig wie auch im Code. Schau mal, ob alles für dich funktioniert.

**Comment by mattreim** [comment]
Die Instanzeinstellungen können jetzt richtig gespeichert werden.
