### ISSUE TITLE
Please fix issues reported by adapter checker

### ISSUE THREAD

**Issue by mcm1957** [tp1de/ioBroker.ems-esp#64]
❗ [E033] @iobroker/adapter-core 3.0.3 specified. 3.1.4 is required as minimum, 3.1.4 is recommended. Please update dependencies at [package.json](https://github.com/tp1de/ioBroker.ems-esp/blob/master/package.json)
based UI
 👀 [W184] "common.materialize" is deprecated for admin >= 5 at [io-package.json](https://github.com/tp1de/ioBroker.ems-esp/blob/master/io-package.json). Please use property "adminUI".
 👀 [W505] setTimeout found in "main.js", but no clearTimeout detected
-> consider adapter.delay(..) / this.delay(...) instead of sleep

**Comment by tp1de** [comment]
@mcm1957 

Ich habe die 3 Anforderungen umgesetzt. Nun habe ich noch eine Frage zum adapter.delay(..):
Muss adapter.delay in async functions mit await aufgerufen werden?

**Comment by mcm1957** [comment]
delay retourniert ein promise. Also JA.

https://github.com/ioBroker/ioBroker.js-controller/blob/8be449d5c8664fd271d87f36dc8d70da8dc119dd/packages/adapter/src/lib/adapter/adapter.ts#L2660
