### ISSUE TITLE
ems-esp.0.gateway.DateTime

### ISSUE THREAD

**Issue by Tim19791** [tp1de/ioBroker.ems-esp#65]
with version 3.4.1 "ems-esp.0.gateway.DateTime" is no longer updated

**Comment by tp1de** [comment]
I checked and I can confirm that no gateway states are updated or created anymore for releases > 3.0.3
Neither me nor any other user has recognized until now. But I got error messages with 3.0.3 for decryption of gateway data.

I will check what needs to be done.

**Comment by tp1de** [comment]
With version 3.4.3 it should work again.
