### ISSUE TITLE
wrong formatting options for api/mqtt bool format in ems-esp settings -> correct: 1/0

### ISSUE THREAD

**Issue by unstressable** [tp1de/ioBroker.ems-esp#67]
When upgrading from 3.2.1 to 3.3.0 or later this error appears in the log and the adapter has no connection to ems-esp Box:

`wrong formatting options for api/mqtt bool format in ems-esp settings -> correct: 1/0`

What is the workaround?

ioBroker and all packages are up-to-date. ioBroker runs in Docker.

**Comment by tp1de** [comment]
As described within docu ems-esp settings are mandatory

**Comment by unstressable** [comment]
Which settings?
All is set, it works with older versions.

**Comment by tp1de** [comment]
Read the PDF docu. Ems-esp settings
