### ISSUE TITLE
Native boolean values are converted into numbers which are written as numbers into database (influxdb)

### ISSUE THREAD

**Issue by harvey637** [tp1de/ioBroker.ems-esp#7]
Hi,
the bug:
some values are booleans in emsep32 (eg. in emsep32 v3.4b17) but displayed as number

versions: 
ems-esp32: 3.4b17 (boolean format: true/false, enum format: Index)
iobroker admin 5.4.9
iobroker ems-esp: 1.12.1 (not km200 formating)
iobroker echarts: 1.0.7

this is an iobroker native datapoint for "hpheatingon":
```
{
  "_id": "ems-esp.0.boiler.hpheatingon",
  "type": "state",
  "common": {
    "id": "boiler.hpheatingon",
    "name": "ems: hp heating",
    "type": "number",
    "read": true,
    "write": false,
    "role": "value",
    "states": {
      "0": "Off",
      "1": "On"
    },
    "min": 0,
    "max": 1
  },
  "native": {
    "ems_type": "boolean",
    "ems_command": "hpheatingon",
    "ems_device": "boiler",
    "ems_id": "",
    "ems_api": "V3"
  },
  "from": "system.adapter.ems-esp.0",
  "user": "system.user.admin",
  "ts": 1652782708358,
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}
```

The "ems_type: boolean" is converted into a "type: number" with the states "0: Off", "1: On". With this setting the native boolean values are stored as numbers in influxdb and consequently handled as numbers in following applications like echarts.

It is more or less an optical problem, as true/false or On/Off is also handled as 1/0, so lines/steps in echarts are ok. But the reading of a chart with "Heating On: 0" and "Heating On: 1" is less intuitive as "Heating On: TRUE" or "Heating On: FALSE". (Or even better "Heating: On" and "Heating: Off", as all the info is there.

thank you
Harvey

**Comment by tp1de** [comment]
Yes you are right. I did this to have better way of graphical scaleability within flot graphs.
So all ems-esp boolean values are converted into numbers with 2 states: 1:On / 0:Off.

I am not sure to change this or make this configurable. Do you really need this?

**Comment by tp1de** [comment]
In the ioBroker Object-Browser you will see On / Off anyhow:

![image](https://user-images.githubusercontent.com/36480251/168801207-6523f073-8187-4021-bac0-b82b5da1d6d3.png)

... and in vis you can select any text you want.

**Comment by harvey637** [comment]
Hi,
thank you for the quick response!

Hmmmm, no, I dont really need this and I am not shure about the conversion of my history in influxdb.

As said it is a bit of optical enhancement. Normally I prefer to use variables of best fitting type, which is the native boolean. Otherwise in echarts it does not matter, as everything is numbers, as long as it gets to the graph. If you have the last value as part of the legend it gets tricky to use the right words. Also some On/Off automatism might be used in iobroker-vis for booleans. 

As you just edited about the suggested boolean format in emsp32: I was the one who requested the separation of the boolean representation to be handled differently in emsp-dashboard an emsp-api :-) (around ~ 3.4b12)

For the optical reason behind this see:
![Image 005](https://user-images.githubusercontent.com/10156426/168801364-abb571ea-2375-4fea-a99d-07c5e1a29a34.png)

You see the "open window: TRUE", but "Heizung an: 0". Same problem elseware, as the WINDOWS.STATE is physically boolean, and converted into nambers :-(

**Comment by tp1de** [comment]
verstehe ich .... kann natürlich auch boolean in true / false einbauen - per parameter.  Soll ich?

**Comment by harvey637** [comment]
Moin,
vielleicht besser nicht.
- vielleicht gibt es Geräte, bei denen ein Typ nur zwei Stellungen hat (also booloean), ein anderer Typ die selbe Variable aber mit mehreren Stellungen, also nur number/enum passt. Etwa eine WP, eine Serie kann nur heizen (an/aus), eine andere  heizen/kühlen/lüften ....
- irgendwie möchte ich ungerne meine Werte des letzen Jahres verlieren, denn ich müsste ja den Typ in influxdb ändern, keine Ahnung, ob das verlustfrei geht.
- viele andere HM-Gerräte sind da auch ähnlich unspezifisch, ein Fensterkontakt hat halt magnetisch Kontakt oder nicht, ist aber auch Nummer 0/1 (konkret aus HM-IP Wandregler .1.WINDOWS_STATE)
- Der Urlaub kommt aus dem SET_POINT_MODE, kann also auch 0-3 (manuell, Urlaub, Party, Boost?) sein, also ganz anders
- der Text ist spezifisch, wenn er genau passen soll, also Heizung an/aus, Fenster offen/geschlossen, Urlaub ja/nein ....

Insbesonders kann ich mir nur schwer vorstellen, wie man ein Konzept inkl. sprachvarianten ENUMS (als noch komplexer als booleans) überall umsetzen will, ist halt viel Engagement und selten gewürdigt.

Keep It Small Simple ... widerspricht all zu vielen Parametern, breaking changes und so.

Danke für Dein Ohr
cu
Harvey

**Comment by harvey637** [comment]
Hi,
mache ich mal wegen Unbedeutung zu.
Soviele andere Baustellen mit ähnlichem Inhalt, manchmal denke ich fast, das ganze boolean nutzt wenig, als 0/1 wäre es einfacher und wird ja auch so gehandhabt. Es sind vielleicht eher Anpassungen an der Ausgabefront (echarts ...), die die Lesbarkeit und Interpretierbarkeit verbessern und nicht ob in der Datenbank 0/1 oder false/true steht.
Siehe meine Konterbunt Legende :-)
danke und ciao
Harvey
