### ISSUE TITLE
Iobroker warning

### ISSUE THREAD

**Issue by tom-da-bomba** [tp1de/ioBroker.ems-esp#82]
Hello

I love the adapter, its very helpful. 

I get in iobroker a warning, that <html><body>    | getOneCachedData: got null states 1 times for ems-esp.0.boiler.burngas
-- | --

I do not record a variable, whoch ich called burngas. See attached screenshot. 
![2024-07-01 08_30_01-objects - raspberrypi – Mozilla Firefox](https://github.com/tp1de/ioBroker.ems-esp/assets/174304153/563b859c-3238-487f-9041-6c0ff91f4746)

I guess there is a missmatch.

** Releated to gateway(s) and/or adapter configuration

B Which version of the ems-esp adapter are you using?  3.5.0
C is this bug related to the ems-esp or km200 gateway? (which gateway hardware are you using?) ems-esp
D please descripe software versions of the ems-esp firmware and/or km200 gateway   EMS-ESP Version 3.6.5
E please post screenshot(s) of the adapter config
attached 
![2024-07-01 08_33_58-instances - raspberrypi – Mozilla Firefox](https://github.com/tp1de/ioBroker.ems-esp/assets/174304153/ce5be492-c765-480e-a660-847c4d21cadd)
![2024-07-01 08_33_39-instances - raspberrypi – Mozilla Firefox](https://github.com/tp1de/ioBroker.ems-esp/assets/174304153/5db009aa-8556-4381-8c19-061509dc888c)
![2024-07-01 08_33_00-instances - raspberrypi – Mozilla Firefox](https://github.com/tp1de/ioBroker.ems-esp/assets/174304153/dc9650ae-c9a5-43ec-a390-afc5c4fd61b3)

**Expected behavior**  
no waring of non existing variables

**Additional context**  
Many thnaks for your help

**Comment by tp1de** [comment]
Ich antworte mal auf Deutsch:

Der Fehler kommt aus der Statistik-Funktion. Ich bin erstaunt, dass es "boiler.burngas" bei dir nicht gibt. Dann funktioniert die Statistik-Funktion auch nicht richtig. D.h. aktuell solltest  du die Funktion deaktivieren. Ich muss abklären, ob die Statistik-Funktion ohne burngas überhaupt Sinn ergibt.

Ferner fällt mir auf, dass du die Berechnung des Kesselwirkungsgrades aktiviert hast. Es gibt aber keine Rücklauftemperatur und du hast die Werte je Temperaturbereich nicht angepasst. Die musst du aus dem Datenblatt deines Kessels übernehmen. 
So macht die Berechnung des Wirkungsgrades keinen Sinn.

Welchen Kessel hast du?

**Comment by tp1de** [comment]
Keine Reaktion?????
