### ISSUE TITLE
Format `CMD` implementieren

### ISSUE THREAD

**Issue by mattreim** [tp1de/ioBroker.ems-esp#83]
Mit der Version 3.7.0-dev.22 wurde `remotetemp` von `INT16` auf `CMD` umgestellt und ich kann es jetzt leider nicht mehr nutzen. Hier noch weitere:

- `thermostat/hc<x>/remotetemp`
- `boiler/reset`
- `boiler/hpshutdown`

Ich habe auch schon bei [EMS-ESP](https://github.com/emsesp/EMS-ESP32/pull/1843) angefragt.
 
Vielen Dank

**Comment by mattreim** [comment]
Hier steht Befehl:
![EMS-Befehl](https://github.com/tp1de/ioBroker.ems-esp/assets/80219712/0549e9e2-658b-4810-95cd-9190cdb395de)

Mit "type: command":
![EMS-Reset](https://github.com/tp1de/ioBroker.ems-esp/assets/80219712/81ced7cf-387c-40b7-844c-fbffad73e08f)

**Comment by tp1de** [comment]
Bitte etwas ausführlicher .... ich kann nicht folgen

**Comment by mattreim** [comment]
Aber genau darum geht es, wenn es nicht angelegt wird kann ich auch keinen Wert setzen. Zuvor war in "remotetemp" ein Wert enthalten und jetzt ist es ein Eingabefeld.

**Comment by tp1de** [comment]
> Aber genau darum geht es, wenn es nicht angelegt wird kann ich auch keinen Wert setzen. Zuvor war in "remotetemp" ein Wert enthalten und jetzt ist es ein Eingabefeld.

D.h. "remotetemp" ist bei dir in .../api/thermostat enthalten?   Bei mir nicht!

**Comment by mattreim** [comment]
EMS-ESP emuliert ein Thermostat mit dem Werte (z.B. Temperatur/Luftfeuchtigkeit) an die Heizung übergeben werden kann. Es muss erst eingestellt werden.

**Comment by tp1de** [comment]
Soweit klar. Dann ist aber bei dir bei ..../api/thermostat  der "remotetemp" Eintarg vorhanden ? JA oder Nein?

**Comment by mattreim** [comment]
v21: Ja
v22: Nein

**Comment by tp1de** [comment]
Da müssen die ems-esp Entwickler anpassen. Den "type": "command"  für diese Felder halte ich für falsch und uneindeutig.
Aber Inhalt  ist mal  "number" für remotetemp und mal "enum" z.B. für boiler/reset. 
Für Home Assistant (MQTT) bleibt es eh bei den alten Formaten. Also warum API ändern ?????

**Comment by mattreim** [comment]
Danke
