### ISSUE TITLE
Automatic polling not working

### ISSUE THREAD

**Issue by MrX552** [tp1de/ioBroker.ems-esp#97]
Since one of the last updates (not sure when exactly) the automatic polling is not working anymore. On adapter restart all data from ems-esp are correctly received but later on no more now data. Receiving data via MQTT is working.

ioBroker log looks like this:

ems-esp.0 | 2024-08-10 21:56:51.962 | info | ems : polling every 60 secs
ems-esp.0 | 2024-08-10 21:56:51.962 | info | end of initializing EMS-ESP states
ems-esp.0 | 2024-08-10 21:56:39.747 | info | url1:http://192.168.178.150/api/thermostat
ems-esp.0 | 2024-08-10 21:56:21.599 | info | url1:http://192.168.178.150/api/boiler
ems-esp.0 | 2024-08-10 21:56:19.842 | info | url:http://192.168.178.150/api/system
ems-esp.0 | 2024-08-10 21:56:19.841 | info | start initializing EMS-ESP states
ems-esp.0 | 2024-08-10 21:56:19.840 | info | EMS-ESP API version: 3.6.5
ems-esp.0 | 2024-08-10 21:56:19.839 | info | formatting options for ems-esp gateway checked --> OK
ems-esp.0 | 2024-08-10 21:56:19.667 | info | starting. Version 4.6.2 in /opt/iobroker/node_modules/iobroker.ems-esp, node: v18.19.1, js-controller: 6.0.10
ems-esp.0 | 2024-08-10 21:56:13.271 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
ems-esp.0 | 2024-08-10 21:56:13.270 | info | terminating
ems-esp.0 | 2024-08-10 21:56:13.268 | info | Got terminate signal TERMINATE_YOURSELF

(restarted the adapter to get the log)

Joern

**Comment by git-ZeR0** [comment]
can confirm it. Same problem here.

**Comment by git-ZeR0** [comment]
After i installed v4.4.0 for testing purposes (https://github.com/tp1de/ioBroker.ems-esp/releases/tag/v4.4.0) and polling seems to be working as intended again.

**Comment by tp1de** [comment]
I found the error. 
This was due to changed data names and structure with actual 3.7. dev version of EMS-ESP gateway.

Should be corrected now by newest ioBroker adapter version 4.6.4 - I just released. 
Either install from Github or wait until it is available in beta repo late afternoon today.
