### ISSUE TITLE
Search for extended EMS+ entities (switchPrograms and holidayModes) are disabled for now

### ISSUE THREAD

**Issue by tp1de** [tp1de/ioBroker.ems-esp#98]
https://github.com/emsesp/EMS-ESP32/issues/1935

has indicated that the search for extended entities might bring the EMS-ESP gateway to crash because of memory problems.
There is no solution until now - I have disabled this function within ioBroker adapter until a better solution is available.

P.S.: It will continue to work for those users who are using it today.

**Comment by MichaelDvP** [comment]
Seems you are polling very fast, maybe flooding the TCP stack. Can you add more delay.
```
2024-08-14 08:21:51.109 DEBUG 345: [command] Called command system/response (Hole Antwort)
2024-08-14 08:21:51.144 DEBUG 346: [command] Called command system/response (Hole Antwort)
```
this is just 35ms between the two polls.

The other isue are: with 2 thermostats it does not send the correct deviceID (in this case 0x10 is master) and sends NaN as deviceID. I'll check what ems-esp do with this.

**Comment by tp1de** [comment]
> Seems you are polling very fast, maybe flooding the TCP stack. Can you add more delay.

I will check

> The other isue are: with 2 thermostats it does not send the correct deviceID (in this case 0x10 is master) and sends NaN as deviceID. I'll check what ems-esp do with this.

Yes the function is not able to work with more then 1 thermostat.

I am thinking about disabling the function until we have a working solution within EMS-ESP to read the data by API get.
(no send / response logic anymore)

**Comment by proddy** [comment]
> I am thinking about disabling the function until we have a working solution within EMS-ESP to read the data by API get.
(no send / response logic anymore)

I remember Michael adding the send/response logic because of ioBroker. But happy to remove it and replace it. Do you have any suggestions on how this could be implemented? Perhaps have EMS-ESP Push changes directly via SSE/WebSocket? Or integrate this into a system command which can be called in the Scheduler to POST the data to another IP address?

**Comment by tp1de** [comment]
@proddy 
I have disabled the search for switchPrograms and holidayModes within my last ioBroker adapter version, because I want to upgrade the stable version soon. Most ioBroker users are still using the stable adapter version 3.5.0 but have installed dev versions of EMS-ESP.  
This combination braught quite some difficulties and instabilities. I need to think how to minimize my efforts to keep the ioBroker adapter alive and working with different firmware versions. 
Maybe stable ioBroker versions should only work with stable EMS-ESP versions? (dev versions to be rejected??)

4.8.0 should be the next stable version of the ioBroker adapter - but without the extended search functions.

The switchPrograms are discussed with @MichaelDvP in https://github.com/emsesp/EMS-ESP32/issues/1594 .
Michael is making good progress to implement the function within EMS-ESP. 
When this ready and tested I will implement within ioBroker adapter.
